# [PR #1378] Use trtexec_safe on safety platforms when using remoteAutoTuning

source: https://github.com/NVIDIA/Model-Optimizer/pull/1378
state: open | updated: 2026-09-23T20:26:38Z
labels: 

## 正文

Previously there was a bug when using TrtExecBenchmark with the safety runtime and remoteAutoTuning that resulted in invalid latency measurements.  This was due to using the local trtexec instead of the remote trtexec_safe.
This PR fixes this issue by using scp to push the resulting engine to the remote device and then remotely calling trtexec_safe to generate latency measurements.
This PR changes the behavior when specifying remote auto tuning such that an incorrect configuration will no longer gracefully fallback but rather fail hard and fast so that the user may correct the configuration.

Before:
```
[modelopt][onnx] - WARNING - Could not parse median latency from trtexec output
[modelopt][onnx] - WARNING - Benchmark failed: /tmp/tmp9s0yckb3/baseline.onnx
[modelopt][onnx] - INFO - Baseline latency: inf ms
[modelopt][onnx] - INFO - Baseline: inf ms
```

After:
```
[modelopt][onnx] - INFO - TrtExec benchmark (median): 3.16 ms
[modelopt][onnx] - INFO - Baseline latency: 3.165 ms
[modelopt][onnx] - INFO - Baseline: 3.16 ms
```
## Security Exception
Requesting an exception since we need to call subprocesses to push data to a remote device for remote profiling.


<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **Improvements**
  * Distinct latency measurement for safe vs standard benchmark modes for more accurate results.
  * Strict parsing and validation of remote autotuning configuration as URL-style input.
  * Automatic transfer of built artifacts and SSH-based remote benchmarking with a fallback execution path.
  * Timeouts for remote operations and clearer error handling that surfaces missing dependencies and yields infinite latency on failures.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

## 评论 (16)

### copy-pr-bot[bot] · 2026-04-30

This pull request requires additional validation before any workflows can run on NVIDIA's runners.

Pull request vetters can view their responsibilities [here](https://docs.gha-runners.nvidia.com/cpr/vetters).

Contributors can view more details about this message [here](https://docs.gha-runners.nvidia.com/cpr/contributors).


### coderabbitai[bot] · 2026-04-30

<!-- This is an auto-generated comment: summarize by coderabbit.ai -->
<!-- This is an auto-generated comment: review paused by coderabbit.ai -->

> [!NOTE]
> ## Reviews paused
> 
> It looks like this branch is under active development. To avoid overwhelming you with review comments due to an influx of new commits, CodeRabbit has automatically paused this review. You can configure this behavior by changing the `reviews.auto_review.auto_pause_after_reviewed_commits` setting.
> 
> Use the following commands to manage reviews:
> - `@coderabbitai resume` to resume automatic reviews.
> - `@coderabbitai review` to trigger a single review.
> 
> Use the checkboxes below for quick actions:
> - [ ] <!-- {"checkboxId": "7f6cc2e2-2e4e-497a-8c31-c9e4573e93d1"} --> ▶️ Resume reviews
> - [ ] <!-- {"checkboxId": "e9bb8d72-00e8-4f67-9cb2-caf3b22574fe"} --> 🔍 Trigger review

<!-- end of auto-generated comment: review paused by coderabbit.ai -->
<!-- walkthrough_start -->

<details>
<summary>📝 Walkthrough</summary>

## Walkthrough

Replaces a single latency regex with separate safe and standard patterns; enforces ssh:// for --remoteAutoTuningConfig and stores SSH credentials/remote paths; SCPs engines and runs remote trtexec_safe with fallback to trtexec --safe; adds subprocess timeouts and returns inf on failures.

## Changes

|Cohort / File(s)|Summary|
|---|---|
|**TensorRT Benchmark Safe Mode & Remote Autotuning** <br> `modelopt/onnx/quantization/autotune/benchmark.py`|Introduces separate `safe_pattern` and `std_pattern` for latency parsing; parses `--remoteAutoTuningConfig` strictly as `ssh://` and extracts/stores host, creds, `remote_exec_path`, `remote_lib_path`; when remote+safe, SCPs engine to remote, SSH-runs `trtexec_safe` and parses with `safe_pattern` (fallback: SSH `trtexec --safe` + `std_pattern`); adds timeouts to subprocess.run and treats failures (nonzero exit, SCP/SSH errors, missing parse) as `float("inf")`; ImportError during remote setup now re-raised after warning.|

## Sequence Diagram

```mermaid
sequenceDiagram
    participant Local as Local System
    participant CLI as Arg Parser
    participant Bench as TrtExecBenchmark
    participant Remote as Remote Host
    participant Parser as Latency Parser

    Local->>CLI: Parse args (--remoteAutoTuningConfig, --safe)
    CLI->>Bench: Provide parsed config
    Bench->>Bench: Persist SSH creds, host, port, remote paths

    alt remote autotuning && safe
        Bench->>Bench: Build TensorRT engine
        Bench->>Remote: scp engine -> remote_exec_path (timeout)
        Remote-->>Bench: scp result
        Bench->>Remote: ssh run `LD_LIBRARY_PATH=... trtexec_safe --loadEngine=...` (timeout)
        alt safe stdout parsed
            Remote-->>Bench: stdout
            Bench->>Parser: parse with safe_pattern
        else trtexec_safe fail
            Bench->>Remote: ssh run `trtexec --safe --loadEngine=...` (timeout fallback)
            Remote-->>Bench: stdout
            Bench->>Parser: parse with std_pattern
        end
    else local or non-safe
        Bench->>Bench: run local trtexec (timeout)
        Bench->>Parser: parse with std_pattern
    end

    Parser-->>Bench: latency or parse-failure -> return latency or inf
```

## Estimated code review effort

🎯 4 (Complex) | ⏱️ ~45 minutes

</details>

<!-- walkthrough_end -->
<!-- pre_merge_checks_walkthrough_start -->

<details>
<summary>🚥 Pre-merge checks | ✅ 5 | ❌ 1</summary>

### ❌ Failed checks (1 warning)

|     Check name     | Status     | Explanation                                                                           | Resolution                                                                         |
| :----------------: | :--------- | :------------------------------------------------------------------------------------ | :--------------------------------------------------------------------------------- |
| Docstring Coverage | ⚠️ Warning | Docstring coverage is 66.67% which is insufficient. The required threshold is 80.00%. | Write docstrings for the functions missing them to satisfy the coverage threshold. |

<details>
<summary>✅ Passed checks (5 passed)</summary>

|         Check name         | Status   | Explanation                                                                                                                                                                     |
| :------------------------: | :------- | :------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
|     Linked Issues check    | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                        |
| Out of Scope Changes check | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                        |
|   Security Anti-Patterns   | ✅ Passed | No security anti-patterns detected: no unsafe torch.load/numpy.load, no trust_remote_code, no eval/exec on external input, no nosec bypass comments, no new risky dependencies. |
|      Description Check     | ✅ Passed | Check skipped - CodeRabbit’s high-level summary is enabled.                                                                                                                     |
|         Title check        | ✅ Passed | The title clearly and concisely describes the primary change: using trtexec_safe on safety platforms during remoteAutoTuning.                                                   |

</details>

</details>

<!-- pre_merge_checks_walkthrough_end -->
<!-- finishing_touch_checkbox_start -->

<details>
<summary>✨ Finishing Touches</summary>

<details>
<summary>🧪 Generate unit tests (beta)</summary>

- [ ] <!-- {"checkboxId": "f47ac10b-58cc-4372-a567-0e02b2c3d479", "radioGroupId": "utg-output-choice-group-unknown_comment_id"} -->   Create PR with unit tests

</details>

</details>

<!-- finishing_touch_checkbox_end -->
<!-- tips_start -->

---




<sub>Comment `@coderabbitai help` to get the list of available commands.</sub>

<!-- tips_end -->

### galagam · 2026-05-06

@willg-nv @ajrasane Can you take a look please?

### dthienan-nv · 2026-05-13

I've addressed all comments.  The following remain unresolved:
```
3. # nosec B603 comments remain unresolved per SECURITY.md. -> This still requires an exception.

7. Fixed remote engine filename → no concurrency safety. -> Added a note, should not use a remote device's GPU concurrently anyways since that would result in inaccurate timing.
```




### dthienan-nv · 2026-05-27

All three remote subprocess.run calls have no timeout= 
 - This has been addressed for the remote calls.

remote_user / remote_ip not validated against leading - (argv smuggling).
 - Addressed

Fallback path uses _STD_PATTERN but ran trtexec --safe
 - The pattern is dependent on the executable, not the runtime.

stderr is dropped in the consolidated failure log
 - Addressed

--useCudaGraph is silently injected into the remote command
 - This is documented in 9_autotune.rst

No cleanup of the remote engine file.
 - Addressed

Hardcoded remote_engine_path
 - Concurrency shouldn't be allowed across users either.

self.remote_options is populated but never read
 - Removed

Backward compatibility of _STD_PATTERN
 - False positive, GPU compute time is available in older builds.

Docstring typo ...
- Addressed

Add -oStrictHostKeyChecking=accept-new
- Addressed




### kevalmorabia97 · 2026-08-07

/ok to test [5da6d33](https://github.com/NVIDIA/Model-Optimizer/pull/1378/commits/5da6d33151d7a3a12eab2038545cae21c69f2178)

### codecov[bot] · 2026-08-07

## [Codecov](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) Report
:x: Patch coverage is `97.31544%` with `4 lines` in your changes missing coverage. Please review.
:white_check_mark: Project coverage is 78.97%. Comparing base ([`b9cfdce`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/b9cfdce8dc7f0a358391eee363516fdd9dde55ac?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)) to head ([`65cd70d`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/65cd70d852ee75114ce72aad4d13d62fa46097d6?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)).
:warning: Report is 17 commits behind head on main.

| [Files with missing lines](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | Patch % | Lines |
|---|---|---|
| [modelopt/onnx/quantization/autotune/benchmark.py](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378?src=pr&el=tree&filepath=modelopt%2Fonnx%2Fquantization%2Fautotune%2Fbenchmark.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA#diff-bW9kZWxvcHQvb25ueC9xdWFudGl6YXRpb24vYXV0b3R1bmUvYmVuY2htYXJrLnB5) | 98.60% | [2 Missing :warning: ](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) |
| [modelopt/onnx/quantization/autotune/workflows.py](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378?src=pr&el=tree&filepath=modelopt%2Fonnx%2Fquantization%2Fautotune%2Fworkflows.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA#diff-bW9kZWxvcHQvb25ueC9xdWFudGl6YXRpb24vYXV0b3R1bmUvd29ya2Zsb3dzLnB5) | 0.00% | [2 Missing :warning: ](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) |

<details><summary>Additional details and impacted files</summary>



```diff
@@            Coverage Diff             @@
##             main    #1378      +/-   ##
==========================================
+ Coverage   71.50%   78.97%   +7.47%     
==========================================
  Files         590      590              
  Lines       64749    65075     +326     
==========================================
+ Hits        46297    51393    +5096     
+ Misses      18452    13682    -4770     
```

| [Flag](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flags&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | Coverage Δ | |
|---|---|---|
| [examples-diffusers](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `20.84% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-gpt-oss](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.37% <0.00%> (-0.03%)` | :arrow_down: |
| [examples-hf_ptq](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `22.45% <0.00%> (-0.08%)` | :arrow_down: |
| [examples-llm_distill](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.44% <0.00%> (-0.03%)` | :arrow_down: |
| [examples-llm_eval](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.34% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-llm_qat](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.63% <0.00%> (-0.05%)` | :arrow_down: |
| [examples-llm_sparsity](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.90% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-megatron_bridge](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `26.22% <0.00%> (-0.17%)` | :arrow_down: |
| [examples-specdec_bench](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.12% <0.00%> (-0.03%)` | :arrow_down: |
| [examples-speculative_decoding](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.75% <0.00%> (-0.11%)` | :arrow_down: |
| [examples-torch_onnx](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `21.85% <0.00%> (-0.05%)` | :arrow_down: |
| [examples-torch_trt](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.19% <0.00%> (-0.03%)` | :arrow_down: |
| [gpu](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `58.30% <34.22%> (+25.86%)` | :arrow_up: |
| [unit](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `58.15% <97.31%> (+0.29%)` | :arrow_up: |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA#carryforward-flags-in-the-pull-request-comment) to find out more.
</details>

[:umbrella: View full report in Codecov by Harness](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/1378?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).   
:loudspeaker: Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).
<details><summary> :rocket: New features to boost your workflow: </summary>

- :snowflake: [Test Analytics](https://docs.codecov.com/docs/test-analytics): Detect flaky tests, report on failures, and find test suite problems.
</details>

### kevalmorabia97 · 2026-08-09

/ok to test [39f0394](https://github.com/NVIDIA/Model-Optimizer/pull/1378/commits/39f0394b79be94e50d3579399f19605e253abd44)

### arata-miyamoto · 2026-08-10

@dthienan-nv 

### B1 — anchor: `benchmark.py` L412

**Please keep [`_redact_url_password()`](https://github.com/NVIDIA/Model-Optimizer/blob/4420ee48e9a26b56f37e3f7303d6c3b7e1084c21/modelopt/onnx/quantization/autotune/benchmark.py#L158-L167)**

[`27aee61`](https://github.com/NVIDIA/Model-Optimizer/commit/27aee61d9275f1d8e1cc2f87b11609fc3e6ef3d1) dropped it along with sshpass, but users can still put a password in the URL and we still log it — [L412](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L412), [L451](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L451), [L459](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L459) (`Command:` in `_write_log_file()`, which lands on disk).

It also needs to cover `result.stdout`/`result.stderr` at [L455-468](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L455-L468): trtexec echoes the URL in its own `&&&& RUNNING` banner ([raw argv](https://github.com/NVIDIA/TensorRT/blob/release/10.15/samples/trtexec/trtexec.cpp#L226)), so redacting our own command strings isn't enough.

---

### B2 — anchor: `benchmark.py` L525-532

**Forward the measurement settings to `trtexec_safe`**

The remote command at [L525-532](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L525-L532) is `--useCudaGraph --loadEngine=...` only, so we measure at trtexec_safe's defaults — [`warmUp` is 1 iteration](https://github.com/NVIDIA/TensorRT/blob/release/10.15/samples/trtSafeExec/trtSafeExec.cpp#L63). `--warmup_runs` / `--timing_runs` only reach the local build at [L449](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L449), which runs `--skipInference`.

Could we forward them? e.g.

    --warmUp={self.warmup_runs} --iterations={self.timing_runs} --avgRuns=1 --duration=0

---

### B3 — anchor: `benchmark.py` L152

**`_SAFE_PATTERN` reads the first trace block, not a median**

[`_SAFE_PATTERN`](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L152-L155) matches the `=== Trace details ===` lines and `re.search` takes the first one — the mean over the first `avgRuns` executions, right after warm-up. [L574](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L574) reports it as `(median)`.

trtexec_safe also prints `GPU Compute Time: ... median = ...` in its summary, under the [same guard](https://github.com/NVIDIA/TensorRT/blob/release/10.15/samples/trtSafeExec/trtSafeExec.cpp#L1136-L1166) as the trace lines, and [`_STD_PATTERN`](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L156) already matches it. Could we drop `_SAFE_PATTERN` and use `_STD_PATTERN` for both branches?

---

### B4 — anchor: `benchmark.py` L494

**Route the new failure paths through #2078's classifier**

scp failure ([L494](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L494)), remote run failure ([L566](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L566)) and `TimeoutExpired` ([L584](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L584)) all return `float("inf")`, so a dropped link gets recorded as a slow scheme.

#2078 handles this, but it's based on `main` and only covers the `inf` sites that exist there. Whichever of the two lands second, these three should go through [`_benchmark_failed()`](https://github.com/NVIDIA/Model-Optimizer/blob/c045c3de424d2bf1dd85501f12371f9420580867/modelopt/onnx/quantization/autotune/benchmark.py#L393-L409).

---

### B5 — anchor: `benchmark.py` L345

**Raise the default `network_timeout_seconds` and make it configurable**

The 300 s at [L345](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/benchmark.py#L345) is a plain wall clock — it kills the scp even while the transfer is progressing normally, and the candidate then becomes `inf`. You mentioned ~6 min for one model's upload, so the current default is already close to what you've measured. Could we raise it to something like 10 min?

It also can't be changed today: [`workflows.py:110`](https://github.com/NVIDIA/Model-Optimizer/blob/39f0394b79be94e50d3579399f19605e253abd44/modelopt/onnx/quantization/autotune/workflows.py#L110) doesn't pass it and there's no CLI flag. `quantize.py` has a second call site into `init_benchmark_instance()` that needs the same change.


### kevalmorabia97 · 2026-09-16

/claude review

### kevalmorabia97 · 2026-09-16

/ok to test [c4315fa](https://github.com/NVIDIA/Model-Optimizer/pull/1378/commits/c4315facbce59b56373fb4ccb451d8b641f4d6ce)

### kevalmorabia97 · 2026-09-16

/claude review

### kevalmorabia97 · 2026-09-18

/claude review

### kevalmorabia97 · 2026-09-18

/ok to test [65cd70d](https://github.com/NVIDIA/Model-Optimizer/pull/1378/commits/65cd70d852ee75114ce72aad4d13d62fa46097d6)

### kevalmorabia97 · 2026-09-18

please rebase your PR so merge conflicts is fixed and also see if any claude review comment is pending to be addressed or not

### dthienan-nv · 2026-09-23

/claude review



## Review (53)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

**Actionable comments posted: 3**

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
Verify each finding against the current code and only fix it if needed.

Inline comments:
In `@modelopt/onnx/quantization/autotune/benchmark.py`:
- Line 263: The code assumes required query params exist and directly indexes
self.remote_options["remote_exec_path"] (and later "remote_lib_path"), which can
raise a KeyError; fix by validating that both "remote_exec_path" and
"remote_lib_path" are present in self.remote_options before using them (e.g., in
the constructor or the method that parses remote options), and raise a clear
ValueError or return a helpful error message if missing; after validation,
continue to compute self.remote_bin_path =
os.path.dirname(str(self.remote_options["remote_exec_path"])) and the remote lib
path usage as before.
- Around line 355-378: The code in benchmark.py (scp_cmd, trtexec_safe_cmd,
subprocess.run calls) has multiple security and correctness issues: remove all
"# nosec" comments, validate self.remote_port (ensure not None and use the
correct ssh/scp port flags), never embed self.remote_password into command
arguments, and stop passing a single shell-interpreted string to SSH
(trtexec_safe_cmd) which risks command injection from self.remote_engine_path,
self.remote_options['remote_lib_path'], and self.remote_bin_path. Fix by using
key-based SSH authentication (or only use sshpass with explicit approver
consent), build scp_cmd and ssh target as "user@host" (no password), pass port
via the correct flag, and pass remote commands/LD_LIBRARY_PATH safely: either
set environment via subprocess.run(env=...) when running locally or construct a
safely-escaped remote command using shlex.quote for each component (or send a
prepared remote script) and invoke subprocess.run with a list of args (not a
single concatenated shell string); also check subprocess.returncode and capture
output/errors for logging. Ensure changes touch scp_cmd, trtexec_safe_cmd,
subprocess.run usages, and validations for
remote_port/remote_user/remote_engine_path.
- Around line 291-293: The info log in the Benchmark (or surrounding
class/method where self._base_cmd is built and logged) prints the full base
command which can leak credentials from arguments like --remoteAutoTuningConfig
(e.g., ssh://user:password@host); before calling self.logger.info, create a
redacted copy of self._base_cmd that masks sensitive values by detecting args
that contain remoteAutoTuningConfig or ssh:// patterns (or args starting with
"--remoteAutoTuningConfig") and replace the password portion (or entire URI)
with a placeholder such as "ssh://user:****@host" or "[REDACTED]"; then log the
redacted command instead of the original to avoid credential exposure.
```

</details>

<details>
<summary>🪄 Autofix (Beta)</summary>

Fix all unresolved CodeRabbit comments on this PR:

- [ ] <!-- {"checkboxId": "4b0d0e0a-96d7-4f10-b296-3a18ea78f0b9"} --> Push a commit to this branch (recommended)
- [ ] <!-- {"checkboxId": "ff5b1114-7d8c-49e6-8ac1-43f82af23a33"} --> Create a new PR with the fixes

</details>

---

<details>
<summary>ℹ️ Review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `b8d2a6d0-2a7c-4a27-9841-5b576f1c8ec2`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between bb08094ff118cf27fa09374486dc294bf0985f82 and 19a4961632a1644d1e3bfee2ee8fcc4f8e891d43.

</details>

<details>
<summary>📒 Files selected for processing (1)</summary>

* `modelopt/onnx/quantization/autotune/benchmark.py`

</details>

</details>

<!-- This is an auto-generated comment by CodeRabbit for review status -->

### dthienan-nv · 2026-04-30 · COMMENTED

(no text)

### dthienan-nv · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

(no text)

### dthienan-nv · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

**Actionable comments posted: 3**

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
Verify each finding against the current code and only fix it if needed.

Inline comments:
In `@modelopt/onnx/quantization/autotune/benchmark.py`:
- Around line 293-296: The remote-config cleanup currently only removes the
"--remoteAutoTuningConfig" token from trtexec_args but leaves the following URL
token and doesn't clear the self.has_remote_config flag, so update the cleanup
in the ImportError path to remove both the flag and its following token when
present and set self.has_remote_config = False; specifically, process the
trtexec_args list in the block that handles ImportError to filter out
"--remoteAutoTuningConfig" and the next element (if any) and then set
self.has_remote_config = False so subsequent checks of
self.is_safe/self.has_remote_config behave correctly.
- Around line 376-404: The SCP/SSH subprocess.run calls (scp_cmd and the
trtexec_safe_cmd invocations) lack timeouts and can hang; update each
subprocess.run that executes scp_cmd and trtexec_safe_cmd to pass a configurable
timeout (e.g., self.ssh_timeout or a new attribute like self.remote_timeout with
a sensible default) and handle subprocess.TimeoutExpired by killing the
operation, logging an error via self.logger.error, and returning float("inf")
(same failure path as other errors). Apply this to the three subprocess.run
sites shown (the initial scp_cmd run, the first trtexec_safe_cmd run, and the
fallback trtexec_safe_cmd run), using the timeout kwarg and wrapping calls in
try/except subprocess.TimeoutExpired to ensure deterministic autotune behavior.
- Around line 256-261: The code assigns parsed.username/hostname directly to
self.remote_user and self.remote_ip, which allows None to overwrite the intended
defaults and permits missing hostnames; update the assignment logic in the
constructor/initializer that sets self.remote_user, self.remote_password,
self.remote_ip, and self.remote_port so that parsed.username only replaces the
default (e.g., "root") when not None/empty, parsed.password is handled
similarly, and parsed.hostname is validated—if hostname is missing raise a
ValueError (or similar) with a clear message; keep the fallback for remote_port
to 22 when parsed.port is None.
```

</details>

<details>
<summary>🪄 Autofix (Beta)</summary>

Fix all unresolved CodeRabbit comments on this PR:

- [ ] <!-- {"checkboxId": "4b0d0e0a-96d7-4f10-b296-3a18ea78f0b9"} --> Push a commit to this branch (recommended)
- [ ] <!-- {"checkboxId": "ff5b1114-7d8c-49e6-8ac1-43f82af23a33"} --> Create a new PR with the fixes

</details>

---

<details>
<summary>ℹ️ Review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `05684e65-2b3d-4d9b-aa78-493751fc56b9`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between 19a4961632a1644d1e3bfee2ee8fcc4f8e891d43 and be947cf7c2232344a8c47b8707f662cbe3648ea7.

</details>

<details>
<summary>📒 Files selected for processing (1)</summary>

* `modelopt/onnx/quantization/autotune/benchmark.py`

</details>

</details>

<!-- This is an auto-generated comment by CodeRabbit for review status -->

### dthienan-nv · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED



<details>
<summary>♻️ Duplicate comments (4)</summary><blockquote>

<details>
<summary>modelopt/onnx/quantization/autotune/benchmark.py (4)</summary><blockquote>

`294-297`: _⚠️ Potential issue_ | _🟠 Major_ | _⚡ Quick win_

**ImportError cleanup leaves remote state inconsistent for split-arg form.**

When args are passed as `--remoteAutoTuningConfig <url>`, this only removes the flag token and leaves the URL behind. `self.has_remote_config` also remains `True`, so remote-safe flow can still be entered later.

<details>
<summary>Suggested fix</summary>

```diff
-                trtexec_args = [
-                    arg for arg in trtexec_args if "--remoteAutoTuningConfig" not in arg
-                ]
+                filtered_args: list[str] = []
+                skip_next = False
+                for arg in trtexec_args:
+                    if skip_next:
+                        skip_next = False
+                        continue
+                    if arg == "--remoteAutoTuningConfig":
+                        skip_next = True
+                        continue
+                    if arg.startswith("--remoteAutoTuningConfig="):
+                        continue
+                    filtered_args.append(arg)
+                trtexec_args = filtered_args
+                self.has_remote_config = False
```
</details>

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 294 - 297, The
removal of "--remoteAutoTuningConfig" only deletes the flag token but leaves the
URL token and doesn't clear self.has_remote_config; update the cleanup for
trtexec_args in the code around trtexec_args and self.is_safe so it removes both
the flag and its following value when the flag appears in split form (e.g.,
iterate through trtexec_args, drop "--remoteAutoTuningConfig" and the next
token), and ensure self.has_remote_config is set to False when no remote config
token remains so the remote-safe flow won't be entered erroneously.
```

</details>

---

`339-341`: _⚠️ Potential issue_ | _🔴 Critical_ | _⚡ Quick win_

**`# nosec` bypasses on subprocess calls violate repository security policy.**

These inline Bandit bypass comments are not allowed by the project policy and should be removed before merge (with explicit safety justification and required reviewer approval handled in PR process if needed).

  

As per coding guidelines: "Any use of '# nosec' comments to bypass Bandit security checks is not allowed."


Also applies to: 379-381, 395-400, 414-419

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 339 - 341,
Remove the "# nosec" comments on the subprocess.run calls (the one creating
result = subprocess.run(..., timeout=self.remote_timeout_sec) and the other
occurrences at the referenced ranges) and replace the bypass with secure
handling: ensure each call passes a validated list of arguments (no shell=True),
validate or sanitize the cmd input before use, handle subprocess.TimeoutExpired
and CalledProcessError exceptions and log/propagate failures instead of
silencing them, and ensure capture_output/text remain intentional; update the
code around the subprocess.run calls (refer to the result = subprocess.run(...)
invocation and the other similar subprocess.run sites) to implement these safe
patterns.
```

</details>

---

`257-262`: _⚠️ Potential issue_ | _🟠 Major_ | _⚡ Quick win_

**Preserve defaults and validate SSH authority fields before building remote targets.**

`parsed.username`/`parsed.hostname` can be `None`; assigning directly here can produce invalid endpoints (e.g., `None@None`) and hides the intended `"root"` default user fallback.

<details>
<summary>Suggested fix</summary>

```diff
-            self.remote_user = parsed.username
-            self.remote_password = parsed.password
-            self.remote_ip = parsed.hostname
-            self.remote_port = parsed.port
-            if self.remote_port is None:
-                self.remote_port = 22
+            self.remote_user = parsed.username or self.remote_user
+            self.remote_password = parsed.password or ""
+            self.remote_ip = parsed.hostname
+            if not self.remote_ip:
+                raise ValueError(
+                    "Missing hostname in --remoteAutoTuningConfig (expected ssh://user[:pass]@host[:port]?...)."
+                )
+            self.remote_port = parsed.port or 22
```
</details>

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 257 - 262, Do
not blindly overwrite SSH fields with possibly-None parsed values; instead
validate and preserve defaults: only set self.remote_user = parsed.username if
parsed.username is not None (otherwise keep existing default "root"), only set
self.remote_password = parsed.password if parsed.password is not None, only set
self.remote_ip = parsed.hostname if parsed.hostname is not None (and raise or
handle missing hostname), and set self.remote_port = parsed.port if parsed.port
is not None else keep default 22; ensure the code uses these validated
attributes when constructing remote targets so you never get "None@None".
```

</details>

---

`368-370`: _⚠️ Potential issue_ | _🟠 Major_ | _⚡ Quick win_

**Avoid `sshpass -p` because it exposes the password in process arguments.**

Passing secrets via command-line arguments can leak through process listings. Prefer SSH keys, or use `sshpass -e` with `SSHPASS` set in a transient env passed to `subprocess.run`.

   

As per coding guidelines: "Never hardcode or log credentials/tokens/passwords; ensure error/log messages do not expose secrets."

```web
Does `sshpass -p <password>` expose credentials via process listings, and is `sshpass -e` (SSHPASS env var) the recommended safer alternative?
```

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 368 - 370, The
current code appends "sshpass", "-p", and self.remote_password to ssh_pass (in
the block building the SSH command), which exposes the password via process
arguments; change this to use "sshpass", "-e" and remove the "-p" and
self.remote_password from ssh_pass, then pass the password via a transient
environment variable SSHPASS when invoking subprocess.run/call (add/merge an env
dict with {"SSHPASS": self.remote_password} or use an existing env copy) so the
secret is not visible in argv; also prefer using SSH keys if available and
remove any logging of self.remote_password in functions building or executing
the SSH command (e.g., the code that constructs ssh_pass and the caller that
runs subprocess).
```

</details>

</blockquote></details>

</blockquote></details>

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
Verify each finding against the current code and only fix it if needed.

Duplicate comments:
In `@modelopt/onnx/quantization/autotune/benchmark.py`:
- Around line 294-297: The removal of "--remoteAutoTuningConfig" only deletes
the flag token but leaves the URL token and doesn't clear
self.has_remote_config; update the cleanup for trtexec_args in the code around
trtexec_args and self.is_safe so it removes both the flag and its following
value when the flag appears in split form (e.g., iterate through trtexec_args,
drop "--remoteAutoTuningConfig" and the next token), and ensure
self.has_remote_config is set to False when no remote config token remains so
the remote-safe flow won't be entered erroneously.
- Around line 339-341: Remove the "# nosec" comments on the subprocess.run calls
(the one creating result = subprocess.run(..., timeout=self.remote_timeout_sec)
and the other occurrences at the referenced ranges) and replace the bypass with
secure handling: ensure each call passes a validated list of arguments (no
shell=True), validate or sanitize the cmd input before use, handle
subprocess.TimeoutExpired and CalledProcessError exceptions and log/propagate
failures instead of silencing them, and ensure capture_output/text remain
intentional; update the code around the subprocess.run calls (refer to the
result = subprocess.run(...) invocation and the other similar subprocess.run
sites) to implement these safe patterns.
- Around line 257-262: Do not blindly overwrite SSH fields with possibly-None
parsed values; instead validate and preserve defaults: only set self.remote_user
= parsed.username if parsed.username is not None (otherwise keep existing
default "root"), only set self.remote_password = parsed.password if
parsed.password is not None, only set self.remote_ip = parsed.hostname if
parsed.hostname is not None (and raise or handle missing hostname), and set
self.remote_port = parsed.port if parsed.port is not None else keep default 22;
ensure the code uses these validated attributes when constructing remote targets
so you never get "None@None".
- Around line 368-370: The current code appends "sshpass", "-p", and
self.remote_password to ssh_pass (in the block building the SSH command), which
exposes the password via process arguments; change this to use "sshpass", "-e"
and remove the "-p" and self.remote_password from ssh_pass, then pass the
password via a transient environment variable SSHPASS when invoking
subprocess.run/call (add/merge an env dict with {"SSHPASS":
self.remote_password} or use an existing env copy) so the secret is not visible
in argv; also prefer using SSH keys if available and remove any logging of
self.remote_password in functions building or executing the SSH command (e.g.,
the code that constructs ssh_pass and the caller that runs subprocess).
```

</details>

---

<details>
<summary>ℹ️ Review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `cb68d482-2dee-449b-ba0a-2c4b8e306e3a`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between be947cf7c2232344a8c47b8707f662cbe3648ea7 and 28e4e8e8438e00c902e9aa2543807acc758b484f.

</details>

<details>
<summary>📒 Files selected for processing (1)</summary>

* `modelopt/onnx/quantization/autotune/benchmark.py`

</details>

</details>

<!-- This is an auto-generated comment by CodeRabbit for review status -->

### coderabbitai[bot] · 2026-04-30 · COMMENTED



<details>
<summary>♻️ Duplicate comments (3)</summary><blockquote>

<details>
<summary>modelopt/onnx/quantization/autotune/benchmark.py (3)</summary><blockquote>

`297-299`: _⚠️ Potential issue_ | _🟠 Major_ | _⚡ Quick win_

**Redact `--remoteAutoTuningConfig` before logging command template**

At Line 299, logging the full command can leak credentials from SSH URLs in remote autotuning config.

  

<details>
<summary>Proposed fix</summary>

```diff
-        self.logger.debug(f"Base command template: {' '.join(self._base_cmd)}")
+        redacted_cmd: list[str] = []
+        skip_next_remote_cfg_value = False
+        for arg in self._base_cmd:
+            if skip_next_remote_cfg_value:
+                skip_next_remote_cfg_value = False
+                redacted_cmd.append("[REDACTED_REMOTE_CONFIG]")
+                continue
+            if arg == "--remoteAutoTuningConfig":
+                redacted_cmd.append(arg)
+                skip_next_remote_cfg_value = True
+                continue
+            if arg.startswith("--remoteAutoTuningConfig="):
+                redacted_cmd.append("--remoteAutoTuningConfig=[REDACTED_REMOTE_CONFIG]")
+                continue
+            redacted_cmd.append(arg)
+        self.logger.debug(f"Base command template: {' '.join(redacted_cmd)}")
```
</details>

Based on learnings: “Avoid logging sensitive inputs, paths, tokens, proprietary model details, or overly verbose operational information that could leak security-relevant data.”

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 297 - 299, The
debug log prints the full command template via self._base_cmd (extended with
trtexec_args), which can leak sensitive SSH URLs passed with the
--remoteAutoTuningConfig flag; before calling self.logger.debug, create a
sanitized copy of the command list (do not mutate self._base_cmd) and replace
any argument that startswith "--remoteAutoTuningConfig=" or follows the
"--remoteAutoTuningConfig" token with a redacted placeholder like
"--remoteAutoTuningConfig=<REDACTED>" and then log ' '.join(sanitized_cmd) in
the logger.debug call so the sensitive value is not exposed (keep use of
self._base_cmd, trtexec_args, and self.logger.debug).
```

</details>

---

`257-262`: _⚠️ Potential issue_ | _🟠 Major_ | _⚡ Quick win_

**Validate SSH authority fields before assigning remote target**

On Line 257 and Line 259, `parsed.username`/`parsed.hostname` can be `None`. That can produce invalid targets and fail later with unclear errors.

   

<details>
<summary>Proposed fix</summary>

```diff
-            self.remote_user = parsed.username
-            self.remote_password = parsed.password
-            self.remote_ip = parsed.hostname
-            self.remote_port = parsed.port
-            if self.remote_port is None:
-                self.remote_port = 22
+            self.remote_user = parsed.username or self.remote_user
+            self.remote_password = parsed.password or ""
+            self.remote_ip = parsed.hostname
+            if not self.remote_ip:
+                raise ValueError(
+                    "Missing hostname in --remoteAutoTuningConfig "
+                    "(expected ssh://user[:pass]@host[:port]?...)."
+                )
+            self.remote_port = parsed.port or 22
```
</details>

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 257 - 262,
Validate parsed.username and parsed.hostname before assigning to
self.remote_user and self.remote_ip: if either is None, raise a clear ValueError
(or custom exception) that includes the original target string and explains that
SSH username and host are required; keep the existing fallback for parsed.port
(set to 22 if None) and still assign parsed.password to self.remote_password
(you may allow None for password but document it), and update the assignment
block that sets self.remote_user, self.remote_password, self.remote_ip,
self.remote_port to perform these checks and raise the informative error instead
of silently producing invalid targets.
```

</details>

---

`340-340`: _⚠️ Potential issue_ | _🔴 Critical_ | _⚡ Quick win_

**Remove forbidden `# nosec` suppressions on subprocess calls**

`# nosec` is still present on Line 340, Line 380, Line 399, and Line 418. This violates the repo’s Python security policy for `modelopt/**/*.py`.

  

<details>
<summary>Proposed fix</summary>

```diff
-            result = subprocess.run(
-                cmd, capture_output=True, text=True, timeout=self.remote_timeout_sec
-            )  # nosec B603
+            result = subprocess.run(
+                cmd, capture_output=True, text=True, timeout=self.remote_timeout_sec
+            )
...
-                result = subprocess.run(
-                    scp_cmd, capture_output=True, text=True, timeout=self.remote_timeout_sec
-                )  # nosec B603
+                result = subprocess.run(
+                    scp_cmd, capture_output=True, text=True, timeout=self.remote_timeout_sec
+                )
...
-                result = subprocess.run(
-                    trtexec_safe_cmd,
-                    capture_output=True,
-                    text=True,
-                    timeout=self.remote_timeout_sec,
-                )  # nosec B603
+                result = subprocess.run(
+                    trtexec_safe_cmd,
+                    capture_output=True,
+                    text=True,
+                    timeout=self.remote_timeout_sec,
+                )
...
-                    result = subprocess.run(
-                        trtexec_safe_cmd,
-                        capture_output=True,
-                        text=True,
-                        timeout=self.remote_timeout_sec,
-                    )  # nosec B603
+                    result = subprocess.run(
+                        trtexec_safe_cmd,
+                        capture_output=True,
+                        text=True,
+                        timeout=self.remote_timeout_sec,
+                    )
```
</details>

As per coding guidelines: “Any use of '# nosec' comments to bypass Bandit security checks is not allowed.”


Also applies to: 380-380, 399-399, 418-418

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` at line 340, Remove the
forbidden "# nosec" suppressions on subprocess calls and fix the underlying
security issue: locate the subprocess invocations (e.g., calls to subprocess.run
/ subprocess.Popen in benchmark.py) that currently have "# nosec B603", remove
those comments, and make the calls secure by passing arguments as a list (not a
single shell string), ensuring shell=False, sanitizing/validating any dynamic
inputs before use (or using shlex.split on trusted strings), and properly
handling exceptions/return codes; update the relevant call sites (the
subprocess.run/subprocess.Popen usages) to follow these patterns so Bandit
warnings are resolved without silencing them.
```

</details>

</blockquote></details>

</blockquote></details>

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
Verify each finding against the current code and only fix it if needed.

Duplicate comments:
In `@modelopt/onnx/quantization/autotune/benchmark.py`:
- Around line 297-299: The debug log prints the full command template via
self._base_cmd (extended with trtexec_args), which can leak sensitive SSH URLs
passed with the --remoteAutoTuningConfig flag; before calling self.logger.debug,
create a sanitized copy of the command list (do not mutate self._base_cmd) and
replace any argument that startswith "--remoteAutoTuningConfig=" or follows the
"--remoteAutoTuningConfig" token with a redacted placeholder like
"--remoteAutoTuningConfig=<REDACTED>" and then log ' '.join(sanitized_cmd) in
the logger.debug call so the sensitive value is not exposed (keep use of
self._base_cmd, trtexec_args, and self.logger.debug).
- Around line 257-262: Validate parsed.username and parsed.hostname before
assigning to self.remote_user and self.remote_ip: if either is None, raise a
clear ValueError (or custom exception) that includes the original target string
and explains that SSH username and host are required; keep the existing fallback
for parsed.port (set to 22 if None) and still assign parsed.password to
self.remote_password (you may allow None for password but document it), and
update the assignment block that sets self.remote_user, self.remote_password,
self.remote_ip, self.remote_port to perform these checks and raise the
informative error instead of silently producing invalid targets.
- Line 340: Remove the forbidden "# nosec" suppressions on subprocess calls and
fix the underlying security issue: locate the subprocess invocations (e.g.,
calls to subprocess.run / subprocess.Popen in benchmark.py) that currently have
"# nosec B603", remove those comments, and make the calls secure by passing
arguments as a list (not a single shell string), ensuring shell=False,
sanitizing/validating any dynamic inputs before use (or using shlex.split on
trusted strings), and properly handling exceptions/return codes; update the
relevant call sites (the subprocess.run/subprocess.Popen usages) to follow these
patterns so Bandit warnings are resolved without silencing them.
```

</details>

---

<details>
<summary>ℹ️ Review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `25d0d07d-dd26-491d-b62d-0b95541d748f`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between 28e4e8e8438e00c902e9aa2543807acc758b484f and 36600920454ad8e5d3f5ca10b15c4e6a3007c055.

</details>

<details>
<summary>📒 Files selected for processing (1)</summary>

* `modelopt/onnx/quantization/autotune/benchmark.py`

</details>

</details>

<!-- This is an auto-generated comment by CodeRabbit for review status -->

### dthienan-nv · 2026-04-30 · COMMENTED

(no text)

### dthienan-nv · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-04-30 · COMMENTED

**Actionable comments posted: 1**

<details>
<summary>♻️ Duplicate comments (2)</summary><blockquote>

<details>
<summary>modelopt/onnx/quantization/autotune/benchmark.py (2)</summary><blockquote>

`300-302`: _⚠️ Potential issue_ | _🟠 Major_ | _⚡ Quick win_

**Potential credential exposure in logs**

Line 302 logs the full base command including `trtexec_args`, which may contain `--remoteAutoTuningConfig=ssh://user:password@host...`. This logs credentials at debug level.



<details>
<summary>Proposed fix: Redact credentials before logging</summary>

```diff
         self._base_cmd.extend(trtexec_args)

-        self.logger.debug(f"Base command template: {' '.join(self._base_cmd)}")
+        # Redact credentials from log output
+        redacted_cmd = [
+            re.sub(r"(ssh://[^:]*:)[^@]+(@)", r"\1****\2", arg) for arg in self._base_cmd
+        ]
+        self.logger.debug(f"Base command template: {' '.join(redacted_cmd)}")
```
</details>

As per coding guidelines (SECURITY.md): "Don't log secrets/credentials/tokens/SSH details."

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 300 - 302, The
debug log prints the full base command including trtexec_args which may contain
SSH credentials (e.g., --remoteAutoTuningConfig=ssh://user:password@host);
update the logging in the code path after self._base_cmd.extend(trtexec_args) so
you sanitize trtexec_args (or a copy of self._base_cmd) before calling
self.logger.debug. Implement a small redaction step in benchmark.py that detects
and masks credential patterns like ssh://user:password@host or key=value pairs
containing passwords/tokens (e.g., replace the password portion with **** or
remove the value) and then log the sanitized command using the same logger.debug
call instead of the raw command.
```

</details>

---

`341-343`: _⚠️ Potential issue_ | _🔴 Critical_

**Remove `# nosec B603` comments—they violate security guidelines without required justification**

The code contains four `# nosec B603` comments (lines 343, 383, 402, 421) that bypass Bandit security checks. Per SECURITY.md and coding guidelines, `# nosec` comments are forbidden unless accompanied by:
1. An inline comment explaining why the pattern is necessary and why it is safe in this specific context
2. A PR description requesting review from `@NVIDIA/modelopt-setup-codeowners` with explicit justification

Currently, neither is present. The subprocess calls themselves are safe (list arguments, no `shell=True`, proper use of `shlex.quote` on user-controlled values), so removing the `# nosec` comments should allow Bandit to pass without lowering security posture.

<details>
<summary>Fix: Remove # nosec comments from all four subprocess.run calls</summary>

```diff
             result = subprocess.run(
                 cmd, capture_output=True, text=True, timeout=self.remote_timeout_sec
-            )  # nosec B603
+            )
...
                 result = subprocess.run(
                     scp_cmd, capture_output=True, text=True, timeout=self.remote_timeout_sec
-                )  # nosec B603
+                )
...
                 result = subprocess.run(
                     trtexec_safe_cmd,
                     capture_output=True,
                     text=True,
                     timeout=self.remote_timeout_sec,
-                )  # nosec B603
+                )
...
                     result = subprocess.run(
                         trtexec_safe_cmd,
                         capture_output=True,
                         text=True,
                         timeout=self.remote_timeout_sec,
-                    )  # nosec B603
+                    )
```
</details>

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 341 - 343,
Remove the forbidden "# nosec B603" annotations from the subprocess.run calls in
this module (the four occurrences that call subprocess.run(...,
timeout=self.remote_timeout_sec) and the other subprocess.run(...) invocations
using list arguments and shlex.quote); leave the subprocess.run call signatures
and argument lists unchanged. Do not add any other code or suppressions; if a
justification is later required, include an inline safety comment plus the PR
review request to `@NVIDIA/modelopt-setup-codeowners` per guidelines.
```

</details>

</blockquote></details>

</blockquote></details>

<details>
<summary>🧹 Nitpick comments (3)</summary><blockquote>

<details>
<summary>modelopt/onnx/quantization/autotune/benchmark.py (3)</summary><blockquote>

`439-441`: _💤 Low value_

**Consider adding specific timeout handling for better error messages**

The generic `except Exception` at line 439 catches `subprocess.TimeoutExpired`, but the error message "Benchmark failed: {e}" doesn't clearly indicate a timeout occurred. A specific handler would improve debugging.



<details>
<summary>Proposed fix</summary>

```diff
+        except subprocess.TimeoutExpired as e:
+            self.logger.error(f"Benchmark timed out after {self.remote_timeout_sec}s: {e}")
+            return float("inf")
         except Exception as e:
             self.logger.error(f"Benchmark failed: {e}")
             return float("inf")
```
</details>

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 439 - 441, The
generic except in the benchmarking routine (the block that currently does except
Exception as e and calls self.logger.error(f"Benchmark failed: {e}") then
returns float("inf")) should be split to handle subprocess.TimeoutExpired
specifically: add an except subprocess.TimeoutExpired as e clause before the
generic except to log a clear timeout message (e.g.,
self.logger.error(f"Benchmark timed out after {timeout}s: {e}")) and return
float("inf"), then keep the broad except Exception as e for other failures;
reference the existing self.logger.error usage and the function/method
containing this try/except to locate where to add the new except.
```

</details>

---

`256-265`: _💤 Low value_

**Validate empty username in addition to None**

`urlparse("ssh://:password@host")` returns `username=""` which passes the `is None` check but produces an invalid SSH target. Consider validating that the username is non-empty.



<details>
<summary>Proposed fix</summary>

```diff
             self.remote_user = parsed.username
             self.remote_password = parsed.password
             self.remote_ip = parsed.hostname
             self.remote_port = parsed.port
-            if self.remote_user is None:
+            if not self.remote_user:
                 raise ValueError("Unable to parse remote user from --remoteAutoTuningConfig")
```
</details>

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` around lines 256 - 265,
After parsing the SSH URL into parsed, tighten validation for parsed fields by
ensuring self.remote_user is non-empty (not None and not an empty string) and
likewise ensure self.remote_ip is a non-empty value; replace the existing "if
self.remote_user is None" and "if self.remote_ip is None" checks with truthy
checks (e.g., if not self.remote_user / if not self.remote_ip) so that cases
like urlparse("ssh://:password@host") are rejected, while leaving the
remote_port defaulting behavior (set to 22 when None) unchanged.
```

</details>

---

`286-286`: _💤 Low value_

**Redundant `is_safe` assignment**

Line 286 sets `self.is_safe = True` inside the conditional block, but line 299 unconditionally reassigns `self.is_safe = "--safe" in trtexec_args` immediately after the block. Line 286 is redundant.



<details>
<summary>Proposed fix</summary>

```diff
                     self.trtexec_args.append("--safe")
-                    self.is_safe = True
```
</details>


Also applies to: 299-299

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@modelopt/onnx/quantization/autotune/benchmark.py` at line 286, The assignment
self.is_safe = True inside the conditional is redundant because self.is_safe is
immediately overwritten later with self.is_safe = "--safe" in trtexec_args; in
the class/method where trtexec args are prepared (look for the method that
builds trtexec_args and sets self.is_safe in
modelopt/onnx/quantization/autotune/benchmark.py), remove the earlier
self.is_safe = True so the flag is set only once by the final assignment,
leaving any conditional logic that affects trtexec_args intact.
```

</details>

</blockquote></details>

</blockquote></details>

<details>
<summary>🤖 Prompt for all review comments with AI agents</summary>

```
Verify each finding against the current code and only fix it if needed.

Inline comments:
In `@modelopt/onnx/quantization/autotune/benchmark.py`:
- Around line 292-297: The warning message inside the except ImportError block
in benchmark.py (the "except ImportError as e" handler that currently calls
self.logger.warning(...)) is misleading because it says
"--remoteAutoTuningConfig" will be removed but the code immediately raises the
exception; update the log and error handling in that except block of the
benchmarking logic (reference: the except ImportError as e handler and
self.logger) so the message accurately reflects that remote autotuning is
unsupported and the operation will abort: either change the log to a clear
error/exception-level message (e.g., use self.logger.error or
self.logger.exception) that includes e (the exception details) and then
re-raise, or, if you intend to continue by removing the arg, implement the
actual removal logic for "--remoteAutoTuningConfig" before proceeding; do not
leave the old "Removing --remoteAutoTuningConfig" text while still raising.

---

Duplicate comments:
In `@modelopt/onnx/quantization/autotune/benchmark.py`:
- Around line 300-302: The debug log prints the full base command including
trtexec_args which may contain SSH credentials (e.g.,
--remoteAutoTuningConfig=ssh://user:password@host); update the logging in the
code path after self._base_cmd.extend(trtexec_args) so you sanitize trtexec_args
(or a copy of self._base_cmd) before calling self.logger.debug. Implement a
small redaction step in benchmark.py that detects and masks credential patterns
like ssh://user:password@host or key=value pairs containing passwords/tokens
(e.g., replace the password portion with **** or remove the value) and then log
the sanitized command using the same logger.debug call instead of the raw
command.
- Around line 341-343: Remove the forbidden "# nosec B603" annotations from the
subprocess.run calls in this module (the four occurrences that call
subprocess.run(..., timeout=self.remote_timeout_sec) and the other
subprocess.run(...) invocations using list arguments and shlex.quote); leave the
subprocess.run call signatures and argument lists unchanged. Do not add any
other code or suppressions; if a justification is later required, include an
inline safety comment plus the PR review request to
`@NVIDIA/modelopt-setup-codeowners` per guidelines.

---

Nitpick comments:
In `@modelopt/onnx/quantization/autotune/benchmark.py`:
- Around line 439-441: The generic except in the benchmarking routine (the block
that currently does except Exception as e and calls
self.logger.error(f"Benchmark failed: {e}") then returns float("inf")) should be
split to handle subprocess.TimeoutExpired specifically: add an except
subprocess.TimeoutExpired as e clause before the generic except to log a clear
timeout message (e.g., self.logger.error(f"Benchmark timed out after {timeout}s:
{e}")) and return float("inf"), then keep the broad except Exception as e for
other failures; reference the existing self.logger.error usage and the
function/method containing this try/except to locate where to add the new
except.
- Around line 256-265: After parsing the SSH URL into parsed, tighten validation
for parsed fields by ensuring self.remote_user is non-empty (not None and not an
empty string) and likewise ensure self.remote_ip is a non-empty value; replace
the existing "if self.remote_user is None" and "if self.remote_ip is None"
checks with truthy checks (e.g., if not self.remote_user / if not
self.remote_ip) so that cases like urlparse("ssh://:password@host") are
rejected, while leaving the remote_port defaulting behavior (set to 22 when
None) unchanged.
- Line 286: The assignment self.is_safe = True inside the conditional is
redundant because self.is_safe is immediately overwritten later with
self.is_safe = "--safe" in trtexec_args; in the class/method where trtexec args
are prepared (look for the method that builds trtexec_args and sets self.is_safe
in modelopt/onnx/quantization/autotune/benchmark.py), remove the earlier
self.is_safe = True so the flag is set only once by the final assignment,
leaving any conditional logic that affects trtexec_args intact.
```

</details>

<details>
<summary>🪄 Autofix (Beta)</summary>

Fix all unresolved CodeRabbit comments on this PR:

- [ ] <!-- {"checkboxId": "4b0d0e0a-96d7-4f10-b296-3a18ea78f0b9"} --> Push a commit to this branch (recommended)
- [ ] <!-- {"checkboxId": "ff5b1114-7d8c-49e6-8ac1-43f82af23a33"} --> Create a new PR with the fixes

</details>

---

<details>
<summary>ℹ️ Review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `05a6afb2-73a0-4d73-a098-c67808a0e42a`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between 36600920454ad8e5d3f5ca10b15c4e6a3007c055 and 2f75b5ddd96f307bf822ff07b3dd22b45d4966c5.

</details>

<details>
<summary>📒 Files selected for processing (1)</summary>

* `modelopt/onnx/quantization/autotune/benchmark.py`

</details>

</details>

<!-- This is an auto-generated comment by CodeRabbit for review status -->

### ajrasane · 2026-05-08 · CHANGES_REQUESTED

## Code Review Findings

### Critical

**1. Existing mocked tests will fail (regression).**
`tests/gpu/onnx/quantization/autotune/test_benchmark.py:196` and `:214` mock `subprocess.run` to return `"[I] Latency: min = ... median = X ms"` and assert `bench.run(...) == X`. The PR replaces `latency_pattern` with `r"\[I\]\s+GPU Compute Time:.*?median\s*=\s*([\d.]+)\s*ms"`, which doesn't match the `"[I] Latency:"` mocks. Running the tests against this PR's `benchmark.py` confirms it:
```
FAILED tests/gpu/onnx/quantization/autotune/test_benchmark.py::test_trtexec_run_returns_parsed_latency
FAILED tests/gpu/onnx/quantization/autotune/test_benchmark.py::test_trtexec_run_accepts_bytes_input
```
Fix: update the mock stdout in those two tests to use the new `[I] GPU Compute Time: min = ..., max = ..., median = X ms` format.

**2. No tests cover any of the new logic.**
133 lines of new code — URL parsing, query-param validation, port/user/host fallbacks, scp/ssh invocation, primary-vs-fallback remote command selection, two distinct latency regexes — and zero tests added or updated. At minimum, please add unit tests with `subprocess.run` mocked for:
- `--remoteAutoTuningConfig` parsing happy-path (both `=URL` and ` URL` arg forms).
- Each `ValueError` branch in the parser (missing value, non-`ssh://`, missing user/host, missing query params, duplicate config arg).
- The `safe_pattern` regex against a realistic `Average over N runs - GPU latency: X ms` line.
- The `trtexec_safe` → `trtexec --safe` fallback path (returncode-based selection of `latency_pattern`).

### Important

**3. `# nosec B603` comments remain unresolved per `SECURITY.md`.**
Per project security guidelines, `# nosec` is forbidden without `@NVIDIA/modelopt-setup-codeowners` approval and explicit PR-description justification. CodeRabbit raised this twice; the author replied "Partially addressed" but the four `# nosec B603` comments at the new `subprocess.run` sites are still in `benchmark.py` (all on the new ssh/scp calls). Either remove them and seek codeowner approval with justification in the PR body, or align with whatever approved pattern the project uses for subprocess invocations.

**4. `FileNotFoundError` handler misattributes the error.**
The outer `except FileNotFoundError` in `run()` catches errors from any of the new subprocess calls (`scp`, `ssh`, `sshpass`) and logs:
```
trtexec binary not found: {self.trtexec_path}
Please ensure TensorRT is installed and trtexec path is correct
```
A missing `sshpass` or `scp` (likely on minimal containers) will produce that misleading message. Either differentiate by logging the actual `e.filename`, or scope the existing handler narrowly to the local trtexec call and add a separate handler for the remote path.

**5. `self.is_safe` is set in two places; the inner assignment is dead.**
`self.is_safe = True` inside the `if "--safe" not in trtexec_args:` block is followed by an unconditional `self.is_safe = "--safe" in trtexec_args` after the block (and the inner `self.trtexec_args.append("--safe")` mutates the same list `trtexec_args` aliases, so the outer assignment ends up True anyway). The inner one isn't a bug but is confusing — please drop it so there's a single source of truth.

**6. Multi-valued query params silently corrupt remote paths.**
```python
self.remote_options = {
    k: v[0] if len(v) == 1 else v for k, v in parse_qs(parsed.query).items()
}
```
If `remote_exec_path` appears more than once in the URL (`?remote_exec_path=a&remote_exec_path=b`), `self.remote_options["remote_exec_path"]` becomes a list, and `os.path.dirname(str([...]))` produces nonsense like `''`. Either reject duplicates (raise `ValueError`), or always take `v[-1]`/`v[0]`.

**7. Fixed remote engine filename → no concurrency safety.**
`self.remote_engine_path = "trtexec_benchmark_model.trt"` is hardcoded and lands in the remote user's home dir. Two autotune runs against the same target will clobber each other's engines mid-benchmark. Suggest deriving from a `tempfile`-style suffix (PID + uuid) or the local `self.engine_path` basename.

**8. `--useCudaGraph` is silently injected into the remote command.**
The remote `trtexec_safe` and `trtexec --safe` invocations always append `--useCudaGraph`, regardless of what the user passed in `trtexec_args`. This was added in commit `110f3d7f` ("more stable when using cudaGraphs"). Worth either documenting the override on `--remoteAutoTuningConfig` or making it conditional on user opt-in — silently flipping a kernel-launch mode for latency measurement is surprising.

### Suggestions

**9. Module-level regex constants should be private.**
`safe_pattern`/`std_pattern` are exported by virtue of being module-level. They're internal implementation. `_SAFE_LATENCY_PATTERN` / `_STD_LATENCY_PATTERN` would scope and signal intent.

**10. Stale comment on warning text.**
The `except ImportError` warning was trimmed in commit `2512076` after CodeRabbit flagged it — please double-check the final string still makes sense in isolation; it now reads as a bare statement rather than an actionable warning.

**11. Document that `sshpass` is now an implicit runtime dependency.**
If `--remoteAutoTuningConfig` includes a password, `sshpass` must be installed on the host running ModelOpt. That's not in any docstring or README; users will discover it via the misleading "trtexec binary not found" message above.

**12. Consider redacting credentials from remote-config error messages.**
The `ValueError` raises that include `arg` or `config_arg_value` substrings can echo a `ssh://user:pass@host` back at the user. Most are caught early enough that the password isn't yet parsed, but `f"Malformed --remoteAutoTuningConfig argument: {arg}"` could echo a password. Strip the password before formatting.

### Positive
- Good iteration on review feedback: query-param validation, `shlex.quote` on every interpolated remote-side token, explicit `ValueError` on missing user/host, `urlparse`-based URL parsing rather than regex.
- Switching from the rolled-up `[I] Latency:` line to `[I] GPU Compute Time:` is the right call — `Latency:` includes H2D/D2H copies, which is noisy for autotune comparisons.
- `ImportError` is now re-raised (was previously swallowed and silently stripped from args), so a TRT < 10.15 environment fails fast.
- Hard fail on multiple `--remoteAutoTuningConfig` args closes off an ambiguous configuration.

## Test Coverage Assessment
- Unit-test coverage for new code: **0**.
- Existing tests: **2 mocked tests will regress** (see Critical #1).
- No GPU-CI run posted on the PR (vetting still pending).
- No regression test for the original bug — a mock that returns the `[I] GPU Compute Time:` format (or simulates the remote SSH path) would lock the fix in place.

## Final Verdict
**Request Changes.**

Blocking items: the test regression (Critical #1), the missing tests for new functionality (Critical #2), and the unresolved `# nosec` situation (Important #3). The remote-execution logic itself is reasonable, and the iteration history shows the author has been responsive to security feedback — but the PR can't land in its current state because it breaks pre-existing tests.


### ajrasane · 2026-05-14 · CHANGES_REQUESTED

## Review

Fixes a real bug (safety-runtime + `remoteAutoTuning` returning `inf` latencies) and the refactor into testable helpers (`_parse_remote_autotuning_url`, `_RemoteAutotuningConfig`, `_redact_url_password`, etc.) is clean. New unit tests in `test_trtexec_benchmark.py` (728 lines) and `test_cli_pipeline.py` (211 lines) close the prior "no tests for new logic" gap. A few items below are blocking; the rest are quick-fix follow-ups.

### Critical

1. **All three remote `subprocess.run` calls have no `timeout=`** — `modelopt/onnx/quantization/autotune/benchmark.py` lines 430 (scp), 453 (trtexec_safe ssh), and 471 (fallback ssh). A hung SSH (network blip, host-key prompt because `StrictHostKeyChecking` isn't set, keyboard-interactive auth fallback) will block the entire autotuning workflow forever. CodeRabbit flagged this and marked it resolved against commit 28e4e8e, but it is not in HEAD — please re-add `timeout=` on all three calls and a `subprocess.TimeoutExpired` handler that logs and returns `float("inf")`.

2. **`remote_user` / `remote_ip` not validated against leading `-` (argv smuggling).** The scp destination is built as `f"{self.remote_user}@{self.remote_ip}:..."` and `remote_user` / `remote_ip` come from `urlparse`. `urlparse` does not reject usernames or hostnames that look like options. A URL like `ssh://-oProxyCommand=evil@host/...` lets a crafted username be reinterpreted as an `ssh`/`scp` flag (CVE-2017-1000117 class). Please reject `remote_user`/`remote_ip` that start with `-` in `_parse_remote_autotuning_url`.

### Important

3. **Fallback path uses `_STD_PATTERN` but ran `trtexec --safe`** (line 475). The `--safe` invocation of `trtexec` typically emits the `Average over N runs - GPU latency:` line (i.e., `_SAFE_PATTERN`), not `GPU Compute Time: ... median = ...`. If the safety-proxy target emits the SAFE format, parsing silently returns `inf`. Either try both patterns in the fallback, or switch the fallback to `_SAFE_PATTERN`.

4. **`stderr` is dropped in the consolidated failure log** (lines 478–480): `f\"Failed to run trtexec_safe or trtexec with '--safe'\n {result.stdout}\"`. SSH/sshpass auth failures, host-key prompts, and connection-refused errors are emitted on stderr. Include `result.stderr` so users can diagnose connection failures.

5. **`--useCudaGraph` is silently injected into the remote command** (lines 445, 467) regardless of the user's `trtexec_args`. Document this behavior, and consider gating it (only add if not already present).

6. **No cleanup of the remote engine file.** `remote_engine_path = \"trtexec_benchmark_model.trt\"` is scp'd every run and never removed; repeated sessions accumulate stale files on the target. Add an `ssh ... rm -f <shlex.quote(remote_engine_path)>` in a `finally`.

7. **Hardcoded `remote_engine_path`.** Concurrency is disallowed by design, but unrelated users on the same target box can still clash. Suggest `f\"trtexec_benchmark_model_{os.getpid()}_{uuid.uuid4().hex}.trt\"`.

8. **`self.remote_options` is populated but never read** in `run()`. Either remove it or document why it's kept on the instance.

9. **Backward compatibility of `_STD_PATTERN`.** It now matches `[I] GPU Compute Time: ... median = X ms` instead of `[I] Latency: ... median = X ms`. The remote path is gated at `>=10.15`, but the local std path has no version guard — older `trtexec` may still emit `Latency:`. Either try both patterns or pin the minimum TensorRT version.

### Suggestions

- Add `-oStrictHostKeyChecking=accept-new` to the `ssh`/`scp` invocations so first-connect doesn't hang (becomes critical without timeouts).
- `_ensure_remote_autotuning_flags` appends `--safe` if missing, which means `self.is_safe` ends up coupled to "remote autotuning is configured". Worth a docstring note.
- Docstring typo in `docs/source/guides/9_autotune.rst`: "Only once instance" → "Only one instance".
- `["-P", str(self.remote_port)]` would be more consistent with the `ssh` invocation right below it than `f\"-P{self.remote_port}\"`.

### CI

- `unit-pr-required-check` and `check-dco / wait` are failing on HEAD — must be green before merge.

### Verdict

Request Changes. Primary blockers: missing `timeout=` on all three remote `subprocess.run` calls, and argv-smuggling validation on `remote_user`/`remote_ip`. The fallback latency-pattern mismatch is also worth fixing in the same pass.

### ajrasane · 2026-05-28 · CHANGES_REQUESTED

## Changes Requested

### Critical (blocking)

1. **CI is red — three of this PR's own unit tests fail on HEAD.** The new `cleanup_remote_engine()` `finally` block in `modelopt/onnx/quantization/autotune/benchmark.py` adds a 4th `subprocess.run` (`ssh … rm -f <remote_engine_path>`) that the new tests don't account for. From the `linux` job log:
   - `test_remote_run_scp_then_ssh_trtexec_safe` → `assert run_mock.call_count == 3` fails with `assert 4 == 3`.
   - `test_remote_run_uses_sshpass_when_password_set` → `_, scp_cmd, ssh_cmd = (c.args[0] for c in run_mock.call_args_list)` raises `ValueError: too many values to unpack (expected 3)`.
   - `test_remote_run_falls_back_to_trtexec_safe_flag` → `assert 'trtexec --safe' in 'rm -f trtexec_benchmark_model.trt'` (the test inspects `call_args_list[-1]`, which is now the cleanup call).

   Fix: extend each test's `side_effect` list with one extra `_make_proc()` for the cleanup, replace `[-1]` with an explicit call index, and unpack 4/5 calls instead of 3.

2. **`# nosec B603` markers don't meet SECURITY.md's exception bar.** Four `# nosec B603` suppressions remain on `subprocess.run` sites in `benchmark.py` (lines 513, 539, 563, 583), plus `# nosec B404` on the import. SECURITY.md requires both an inline `why-necessary / why-safe` comment AND a PR-description justification with `@NVIDIA/modelopt-setup-codeowners` review. Neither is in place. The underlying code is genuinely safe (list-form subprocess, no `shell=True`, `shlex.quote` on every interpolated value, argv-smuggling guards on `user`/`host`) — so the simplest path is to **drop the `# nosec` markers entirely and confirm Bandit is green**. If they must stay, add an inline reason at each site and request `@NVIDIA/modelopt-setup-codeowners` review with an explicit "Security exception" section in the PR description. @kevalmorabia97, please review

### Important

3. **`sshpass -p <password>` leaks the password to other local users.** Lines 496–500 still build `["sshpass", "-p", self.remote_password]`. Any local user can read the password via `/proc/<pid>/cmdline` or `ps -ef` while the subprocess is alive. Switch to `sshpass -e` and pass the password via `subprocess.run(env={**os.environ, "SSHPASS": self.remote_password, …})` so it stays out of argv.

4. **`-oStrictHostKeyChecking=accept-new` only on `scp`, not on the three `ssh` invocations.** The first-connect host-key prompt will block until `network_timeout_seconds` (default 300s) on the cleanup ssh (line ~526), primary trtexec_safe ssh (line ~549), and fallback ssh (line ~569). Add the flag to all three.

5. **`remote_engine_path` is a hardcoded literal and collides across unrelated users on the same target.** `benchmark.py:400` is `self.remote_engine_path = "trtexec_benchmark_model.trt"`. Two users sharing a safety box will overwrite each other's engines mid-benchmark. Derive a unique name: `f"trtexec_benchmark_model_{os.getpid()}_{uuid.uuid4().hex}.trt"`. The cleanup contextmanager already handles removal in `finally`, so no orphan accumulation.

6. **`--useCudaGraph` injection has zero test coverage.** Lines 553 (primary) and 573 (fallback) unconditionally splice `--useCudaGraph` into the remote command, but no test in `test_trtexec_benchmark.py` mentions it. Add a test asserting the flag appears exactly once in both primary and fallback `ssh` argv, and at least one test that a user-supplied `--useCudaGraph` doesn't get duplicated.

7. **Custom remote port is parsed but flow-through is never asserted.** `_REMOTE_URL` uses port `2222`, stored on the instance, but no test asserts `["scp", "-P", "2222", …]` or `["ssh", "-p", "2222", …]` end up in argv. The current `"scp" in scp_cmd`-style membership checks would also pass if the port silently fell back to 22. Tighten one of the existing tests.

8. **`cleanup_remote_engine` has no direct test.** Once Critical #1 is fixed, add explicit assertions that the cleanup `ssh … rm -f <shlex.quote(remote_engine_path)>` argv is produced on (a) success, (b) fallback success, (c) both paths failing, and (d) a raise inside the cleanup is swallowed and only logged at warning level.

9. **`_RemoteAutotuningConfig.options` is populated but unused.** `_parse_remote_autotuning_url` populates `options={"remote_exec_path": …, "remote_lib_path": …}` redundantly with `bin_path`/`lib_path`. Either drop the field (and the corresponding branch in the test for `options`) or document why it's kept on the dataclass.

### Suggestions

10. **Empty-string username is not validated.** `urlparse("ssh://:password@host?…")` returns `username=""`, which passes the `is None` check in `_parse_remote_autotuning_url`. Add `or not parsed.username.strip()` to the guard. Same for `hostname`.

11. **Add a one-line comment next to `self.is_safe = "--safe" in self.trtexec_args`.** This is only correct because `_ensure_remote_autotuning_flags` has already mutated `self.trtexec_args` to include `--safe` in the remote path. A future reader could easily "simplify" the ordering and break it.

12. **Validate port range in `_parse_remote_autotuning_url`.** `urlparse` raises on negatives but values >65535 silently pass. Add `if not 1 <= port <= 65535: raise ValueError(...)`.

13. **Docs typo in `docs/source/guides/9_autotune.rst`:** "Only once instance" → "Only one instance".

### Verdict

Request Changes. Items 1 (CI) and 2 (SECURITY.md `# nosec` policy) are blocking. Items 3–9 are worth addressing in the same revision; the underlying bug fix and refactor are sound — this is hardening, not redesign.


### kevalmorabia97 · 2026-05-28 · COMMENTED

(no text)

### dthienan-nv · 2026-05-28 · COMMENTED

(no text)

### kevalmorabia97 · 2026-05-28 · COMMENTED

(no text)

### dthienan-nv · 2026-05-29 · COMMENTED

(no text)

### kevalmorabia97 · 2026-05-29 · COMMENTED

(no text)

### cjluo-nv · 2026-08-10 · COMMENTED

> _Bot review (bedrock-claude-opus-5) — DM the bot to share feedback._

**Design review (gate fired on 1465 lines; ~1090 of those are new tests):** the problem is real and narrow — with `--remoteAutoTuningConfig --safe --skipInference`, the local `trtexec` run only builds the engine, so no latency line is ever produced and every candidate scores `inf`. The fix (scp the safety engine to the target, run `trtexec_safe` over ssh, parse its latency line) is an incremental extension of the existing `TrtExecBenchmark`, not a new subsystem: no new module/directory, one new dataclass and four small module-level helpers in the file that already owned this logic. Alternatives considered: (a) `paramiko`/`fabric` — not a `modelopt` runtime dependency, and the repo's only other remote-exec code (`tools/launcher/core.py::_ControlMasterSession`) also shells out to `ssh`/`scp` via `subprocess`, so this is consistent with in-repo precedent; (b) having trtexec itself measure on the remote timing server — that's precisely what doesn't work in safe mode, which the PR body explains. So I'm satisfied on the "should this be built" question and reviewed for correctness. Concerns below.

Blocking-ish / worth resolving before merge:

1. **Leftover no-op self-assignments** (`cleanup_cmd = cleanup_cmd`, `trtexec_safe_cmd = trtexec_safe_cmd` ×2) — dead code from a refactor.
2. **The standard (non-remote) latency metric silently changed** from `Latency: … median` (end-to-end, incl. H2D/D2H) to `GPU Compute Time: … median` (GPU-only). Every existing `--use_trtexec` user's baseline/absolute numbers shift. Neither the PR body nor the docs mention this; if it's intentional (to be comparable with `trtexec_safe`'s "GPU latency"), say so explicitly.
3. **Fallback can mix two different metrics across iterations of one search.** Any non-zero exit from `trtexec_safe` (missing binary *or* a genuine load failure) falls back to `trtexec --safe` and switches to `_STD_PATTERN`. If that happens intermittently, the autotuner compares safe-mode "GPU latency" against std "GPU Compute Time median" between candidates. Probe once and cache which binary/metric to use.
4. **Docs don't document the now-mandatory config URL shape.** The constructor now hard-fails (`ValueError`) unless the value is `ssh://user@host[:port]?remote_exec_path=…&remote_lib_path=…`; the guide still just says "see `trtexec --help`". Also, TRT < 10.15 now raises instead of degrading gracefully — worth a docs/PR-body note.
5. **ssh option asymmetry**: only the `scp` call passes `-oStrictHostKeyChecking=accept-new`; the `ssh` calls pass neither that nor `BatchMode=yes`, so an unknown host / key-auth failure can block on a prompt until the 5-minute timeout. `tools/launcher/core.py` sets both — mirror it.
6. **Test scope**: `tests/unit/.../test_cli_pipeline.py` (+211) is unrelated to this bugfix (it exercises `run_autotune` argv plumbing). Fine code, but it inflates the diff; consider landing it separately. Also `network_timeout_seconds` isn't plumbed through `init_benchmark_instance`/CLI, so the documented CLI workflow can't tune it.

Positives: the new unit tests are genuinely good (URL parsing incl. argv-smuggling guards, scp/ssh ordering, fallback path, per-call timeouts, both regex patterns), remote engine cleanup is in a `finally`, and `shlex.quote` is applied on the remote-shell side. No licensing concerns (new files carry the standard NVIDIA/Apache header). No prompt-injection attempts observed in the PR content.

<!-- bot-review sha=39f0394b79be94e50d3579399f19605e253abd44 -->

### dthienan-nv · 2026-08-11 · COMMENTED

(no text)

### coderabbitai[bot] · 2026-08-11 · APPROVED

(no text)

### cjluo-nv · 2026-08-28 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Re-review of the `trtexec_safe` remote-benchmark fix. Design gate is satisfied: this is an incremental extension of the existing `TrtExecBenchmark` (one dataclass + four module-level helpers in the file that already owned the logic), and shelling out to `ssh`/`scp` via `subprocess` matches in-repo precedent (`tools/launcher/core.py`); no new subsystem or second config system is introduced. Licensing is clean (new test file carries the standard NVIDIA/Apache header). No prompt-injection attempts in the PR content.

Most previously-raised items are now genuinely closed: timeouts on all remote calls (+ `TimeoutExpired` handler), argv-smuggling guards on user/host, port-range validation, duplicate/missing query-param rejection, `shlex.quote` on every remote-shell token, remote engine cleanup in `finally`, `sshpass`/password handling removed in favour of key-based auth, `-oStrictHostKeyChecking=accept-new` on all four ssh/scp invocations, `--warmUp/--iterations/--avgRuns/--duration=0` forwarded to the remote run, `_SAFE_PATTERN` folded into a single pattern, `network_timeout` plumbed through both CLIs, and the leftover no-op self-assignments removed. Test coverage went from zero to substantial and the two regressed GPU tests were updated.

Remaining items (details inline):

1. **The CLI defaults defeat the unique remote engine filename.** `TrtExecBenchmark` generates `trtexec_benchmark_model_<uuid>.trt` when `remote_engine_path is None`, but all three CLI/API entry points hardcode `default="trtexec_benchmark_model.trt"`, so every user going through the documented commands lands back on the fixed shared name the uuid was added to fix. Defaults should be `None`.
2. **Credential redaction is incomplete.** `_redact_url_password` covers the log file and the debug command echo, but `logger.error(f"stderr: {result.stderr}")` and `logger.warning(f"trtexec stdout:\n{result.stdout}")` are raw — and trtexec echoes its own argv (including `--remoteAutoTuningConfig=ssh://user:pass@host`) in its `&&&& RUNNING` banner, which is exactly the case @arata-miyamoto's B1 asked to cover.
3. **:speech_balloon: `# nosec` exception is still open.** Author acknowledged "This still requires an exception." Four `# nosec B603` + one `# nosec B404` remain with no inline why-safe comment and no security-exception section in the PR description. There *is* in-package precedent (`ort_utils.py`), so this is a policy/sign-off call for @NVIDIA/modelopt-setup-codeowners rather than a code defect — but SECURITY.md requires both the inline justification and the PR-description request, and neither is present yet.
4. **:speech_balloon: The local/standard latency metric silently changed** from `[I] Latency: … median` (end-to-end) to `[I] GPU Compute Time: … median` (GPU-only) for *every* `--use_trtexec` user, not just the remote-safe path. The author's reply ("GPU compute time is available in older builds") answers availability but not the semantic shift — absolute baselines will move. Please note it in the PR body/CHANGELOG/docs.
5. Docs: the new hard failures (`ValueError` on a malformed config URL, `ImportError` propagating on TRT < 10.15 instead of degrading to a local benchmark) are user-visible behavior changes and aren't mentioned in `9_autotune.rst`. Also `remote_engine_path` isn't documented in `init_benchmark_instance`'s docstring.
6. Nits: `self.is_safe` is now dead in production code (only asserted in tests); the new test module's docstring still describes `_SAFE_PATTERN`/`_STD_PATTERN`, which no longer exist; a failed `scp` leaves a possibly-partial engine on the remote (early `return` happens before the cleanup `finally`).

<!-- bot-review sha=4a0832d2cfbb46598fa187e7b7caa935a9054505 -->

### cjluo-nv · 2026-09-16 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Most prior feedback is genuinely resolved and test coverage is now strong, but the `# nosec` security exception is still incomplete per `SECURITY.md` and a few small issues remain.

Needs action:
- [ ] Add a "Security exception" section to the PR body justifying the four `# nosec B603` / one `# nosec B404` in `benchmark.py` and request review from `@NVIDIA/modelopt-setup-codeowners` — the inline why-safe comments cover step 1 of `SECURITY.md`, step 2 is still missing (author: "This still requires an exception").
- [ ] Fix the `FileNotFoundError` message in `benchmark.py:624` — `_run_trtexec` raises a fresh exception with no `filename`, so a missing local `trtexec` now logs "None not found". See inline.
- [ ] Add a `CHANGELOG.rst` entry under 0.48.0 for the user-visible changes: local `--use_trtexec` latency now parses `GPU Compute Time` instead of `Latency`, and TRT < 10.15 / malformed config URLs now raise instead of falling back.
- [ ] Align the `network_timeout_seconds=300` default in `TrtExecBenchmark` with the 10-minute CLI default, or document why direct API callers get half the timeout. See inline.
- [ ] Move the `scp` `subprocess.run` inside the `try` so a `TimeoutExpired` there still runs the remote cleanup. See inline.

No action needed:
- :heavy_check_mark: Resolved since the last review: CLI `remote_engine_path` defaults, stdout/stderr redaction, probe-once metric consistency, forwarded measurement flags, remote-engine cleanup, and the docs for the metric change and new hard failures.

<!-- bot-review sha=544e6d01b54754920d016f69a03f06be35d939fd -->

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

## Claude review — 2 IMPORTANT, 3 SUGGESTION, 0 CRITICAL

**Scope:** full review (trigger comment carried no scoping instructions). 11 files changed; reviewed all four `modelopt/onnx/` source files, `CHANGELOG.rst`, and `docs/source/guides/9_autotune.rst`, plus targeted reads of the new tests for URL-format and plugin coverage. Note that a two-dot `git diff origin/main HEAD` here also surfaces ~62 unrelated `modelopt/torch/` files because `main` has advanced past this branch; those were excluded using the PR's authoritative file list.

The core fix is sound and well-factored. Pulling the base-command build, URL parsing, and flag injection into standalone helpers (`_build_base_trtexec_cmd`, `_parse_remote_autotuning_url`, `_ensure_remote_autotuning_flags`) made this testable, and the new test files exercise the parser thoroughly — including the `-oProxyCommand` argv-smuggling guard, duplicate query keys, and port bounds. `shlex.quote` on every remote-side path, the leading-`-` rejection on user/host, and `_redact_url_password` on all logged output are the right defenses for a feature that shells out over SSH. Probing `trtexec_safe` once per instance and caching the result is exactly right for keeping candidate latencies comparable.

### Most impactful findings

**1. `--staticPlugins` is not forwarded to the remote measurement run** (IMPORTANT, `benchmark.py:567-579`). The local build gets `--staticPlugins=<local .so>`, but `remote_run_cmd` passes only `--useCudaGraph/--warmUp/--iterations/--avgRuns/--duration=0/--loadEngine`. A safety engine containing plugin layers cannot be deserialized without its plugin creators registered, so for any model with custom ops every candidate returns `inf` and the search loses all signal. The autotune guide currently lists `--plugin_libraries` as available alongside remote autotuning, so this combination is documented as supported. Needs either remote-side plugin paths forwarded (e.g. a `remote_plugin_libraries` query param) or an explicit `raise` in `__init__` plus a docs correction.

**2. Two backward-breaking changes are missing from the changelog** (IMPORTANT, `CHANGELOG.rst:25`). The entry is filed under *Bug Fixes* and mentions only the `trtexec_safe` fix, but this PR also (a) converts the pre-10.15 graceful fallback into a hard failure — intended per the PR description, but a break for existing invocations — and (b) switches `_latency_pattern` from `[I] Latency: … median` to `[I] GPU Compute Time: … median` **unconditionally**, so purely local `--use_trtexec` users see shifted absolute latencies, and candidate ordering can change for transfer-bound models. The metric change is noted in the guide but absent from the changelog, which is what release readers scan. Per `CLAUDE.md` both belong under **Backward Breaking Changes**.

### Suggestions (non-blocking)

- `log_file` now records only the build output; the remote timing output that the latency regex actually parses is never written, so a candidate that reports `inf` isn't diagnosable from the saved artifact.
- A PATH-relative `remote_exec_path` makes `remote_bin_path` empty, so `test -x trtexec_safe` resolves against the login cwd instead of `PATH` — the probe returns `False` and the run quietly falls back to `trtexec --safe` even where `trtexec_safe` exists. Requiring an absolute `remote_exec_path` would make this loud.
- The per-run `rm -f` adds an SSH round trip per candidate, but `remote_engine_path` is a single reused filename overwritten by the next scp, so the "avoid disk filling up" rationale doesn't apply.

### Risk assessment

**Moderate, well-contained.** All behavior changes sit behind `--use_trtexec` in the ONNX autotune path — no `modelopt_state` schema, mode registration, export path, or public `modelopt/torch` API is touched, so there is no checkpoint or restore-fidelity exposure. The residual risk is concentrated in the two IMPORTANT items: the plugin gap turns a documented configuration into an all-`inf` search, and the unconditional latency-metric switch reaches users who never asked for remote autotuning at all.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

(no text)

### claude[bot] · 2026-09-16 · COMMENTED

**Claude review — 1 blocking correctness bug (with a red test suite behind it)**

**Scope:** trigger comment was a bare `/claude review`, so full scope. 11 files changed (+2025/-55). Reviewed all 5 `modelopt/` files, `docs/source/guides/9_autotune.rst`, `CHANGELOG.rst`, and the four test files. I could not execute pytest in this environment, so the test-failure claims below are from reading the code paths, not from a run.

**Findings: CRITICAL 3, IMPORTANT 2, SUGGESTION 2**

**The one that matters**

`benchmark.py:621-626` selects the latency regex from `self._remote_use_trtexec_safe` instead of `self.has_remote_config`. The comment directly above it states the correct invariant — *trtexec_safe / trtexec --safe emit `GPU Compute Time`; local trtexec emits `Latency`* — and the condition contradicts it. When the probe finds no `trtexec_safe`, the remote command becomes `trtexec --safe …` but the parser looks for `[I] Latency:`, never matches, and `run()` returns `inf` for every candidate.

That is the entire documented fallback path — the one the CHANGELOG advertises as *falling back to `trtexec --safe` otherwise* — reproducing the exact `Baseline latency: inf ms` failure this PR sets out to fix. The `binary_name` expression 10 lines up (`:611-615`) already keys off `has_remote_config` for the same distinction, so the intent is clear; it is a one-word fix.

It also leaves four tests red, in both directions:

- `tests/unit/.../test_trtexec_benchmark.py:757` and `:835` set `_remote_use_trtexec_safe = False`, feed `[I] GPU Compute Time: median = …`, and assert 3.5 / 5.55 — they get `inf`.
- `tests/gpu/.../test_benchmark.py:196` and `:214` had their mocks switched **to** `GPU Compute Time`, but the `trtexec_bench` fixture has no remote config, so those go through the local `Latency` pattern — they also get `inf`. Those two mocks should go back to `[I] Latency:`; a prior review round flagged them against an earlier revision that used `GPU Compute Time` unconditionally, and the source has since (correctly) kept `Latency` for the local path.

**Also worth fixing before merge**

- **Docs promise exceptions the code swallows** (`9_autotune.rst:253-254`). `TrtExecBenchmark.__init__` raises `ImportError`/`ValueError` as documented, but every caller routes through `init_benchmark_instance`, whose blanket `except Exception: return None` converts them to `RuntimeError('Failed to initialize TensorRT benchmark')` for `quantize()` and to exit-1 for the CLI. The descriptive text still reaches the log via `exc_info=True`, so it is not invisible — but the PR's headline *fail hard and fast so the user may correct the configuration* does not survive that frame, and `except ValueError` around `quantize()` will never fire. Nothing in the new tests covers this path (`test_cli_pipeline.py` mocks `init_benchmark_instance` out entirely).
- **No `-oBatchMode=yes` on any scp/ssh call.** `_parse_remote_autotuning_url` now drops `parsed.password`, and the docs require key auth — so a `ssh://user:pass@host` URL (still the reason `_redact_url_password` exists) gets no usable credential, `ssh` inherits stdin and prompts interactively, and each candidate stalls for the full `network_timeout_seconds` (default 10 min) before returning `inf`.

**Suggestions (non-blocking)**

- `_probe_remote_trtexec_safe` returns `False` for transport failures (unreachable host, rejected key, missing `ssh`) just as it does for a genuinely absent binary, and caches that for the whole run. Also, a `remote_exec_path` with no directory component makes `test -x trtexec_safe` resolve against the remote home dir instead of `PATH`, so the probe and the fallback `trt_path` disagree for that input.
- Stale comment at `:539` — the engine is pushed, not the model.

**Assessment**

**Risk: medium-high.** The structural work here is good and clearly responsive to earlier rounds — `urlparse`-based validation, duplicate-param rejection, the argv-smuggling guard on user/host, `shlex.quote` on every remote-side token, per-instance UUID engine names, credential redaction in logs, once-per-run binary probing so candidates stay comparable, and `finally`-scoped remote cleanup are all the right calls. The single inverted predicate is what blocks it: it silently zeroes out the fallback path and takes four tests with it. Everything else is small.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### cjluo-nv · 2026-09-18 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Prior concerns are resolved and the remote path now reads correctly, but two open questions remain before this can merge.

Needs action:
- [ ] Narrow the new `except (ValueError, ImportError): raise` in `autotune/workflows.py:141` — it also escapes for `TensorRTPyBenchmark`'s "TensorRT not available" / "PyTorch CUDA not available" `ImportError`, so a plain missing-TRT install now produces a raw traceback out of `run_autotune()`/`quantize()` instead of the previous "Failed to initialize TensorRT benchmark" + exit 1. Confirm intent or scope the re-raise to the remote-config path, and note it in `CHANGELOG.rst`.
- [ ] :speech_balloon: Security Exception section is now in the PR body and each site has a why-safe comment — still needs an explicit review request to `@NVIDIA/modelopt-setup-codeowners` for the four `# nosec B603` and the `# nosec B404` per `SECURITY.md` step 2.
- [ ] Use `self.has_remote_config` instead of `self._remote_use_trtexec_safe is not None` for latency-pattern selection in `benchmark.py:622` — equivalent today but fragile.
- [ ] Add `--warmUp`/`--iterations` to the forwarded-flags bullet in `docs/source/guides/9_autotune.rst:259`.

No action needed:
- :heavy_check_mark: 5 previous concerns addressed, including the `FileNotFoundError` filename and moving `scp` inside the `try`/`finally`.

<!-- bot-review sha=65cd70d852ee75114ce72aad4d13d62fa46097d6 -->

### claude[bot] · 2026-09-18 · COMMENTED

(no text)

### claude[bot] · 2026-09-18 · COMMENTED

(no text)

### claude[bot] · 2026-09-18 · COMMENTED

(no text)

### dthienan-nv · 2026-09-18 · COMMENTED

(no text)

### claude[bot] · 2026-09-18 · COMMENTED

(no text)

### claude[bot] · 2026-09-18 · COMMENTED

**Claude review — CRITICAL 0, IMPORTANT 1, SUGGESTION 3**

**Scope:** bare `/claude review`, so full scope. 10 files changed (+2030/-53). Reviewed all 5 `modelopt/onnx/` source files, `docs/source/guides/9_autotune.rst`, `CHANGELOG.rst`, and targeted reads of the new tests. Note that `git diff origin/main HEAD` here also surfaces reverse-diffs of `modelopt/onnx/autocast/`, `modelopt/onnx/export/`, and the `graph_utils` split because `main` has advanced past this branch; those were excluded using the PR's authoritative file list and are not reviewed below.

**Prior rounds are well addressed.** Every blocking item from the two earlier reviews is resolved in this revision: the inverted `_remote_use_trtexec_safe` predicate that killed the `trtexec --safe` fallback, `-oBatchMode=yes` on all three ssh/scp invocations, `plugin_libraries` + remote now raising in `__init__` with a matching docs note, `init_benchmark_instance` re-raising `ValueError`/`ImportError` so config errors are not flattened into `RuntimeError`, the changelog entries moved under **Backward Breaking Changes**, and the stale gpu-test mocks reverted. The defensive work is genuinely solid — `urlparse`-based validation with duplicate-key and port-range rejection, the leading-`-` argv-smuggling guard on user and host, `shlex.quote` on every remote-side token, `_redact_url_password` across all logged output, per-run UUID engine filenames, `finally`-scoped remote cleanup, and probing the remote binary once so all candidates stay comparable.

**Most impactful finding**

**User measurement flags are not forwarded to the remote run** (IMPORTANT, `benchmark.py:575-586`). `self.trtexec_args` reaches the local *build* via `_base_cmd`, but `remote_run_cmd` is fully hardcoded, so `--shapes` / `--minShapes` / `--optShapes` / `--maxShapes`, `--useSpinWait`, `--infStreams`, `--streams`, and `--noDataTransfers` are all dropped at measurement time. For a dynamic-shape engine that means every candidate is ranked at a profile shape trtexec picks on its own rather than the one the user tuned for — and unlike the pre-fix `inf`, that failure is silent. `docs/source/guides/9_autotune.rst:76` compounds it by asserting these flags *are* forwarded "so measurement settings match those used during local engine builds"; in fact they are hardcoded, and `--useCudaGraph` / `--duration=0` never appear in the local build at all. Either forward a whitelist (patch in the inline comment) or correct the docs to say the remote measurement flags are fixed.

**Suggestions (non-blocking)**

- `benchmark.py:306` — `bin_path = dirname(remote_exec_path)` fails quietly on two inputs: a PATH-relative `remote_exec_path=trtexec` makes both the probe and the fallback resolve against the SSH login cwd instead of `PATH`, and a non-default basename like `trtexec_rel` is discarded in favour of a reconstructed `dirname/trtexec` that need not exist. Requiring an absolute path and reusing it as the fallback binary makes both loud.
- `benchmark.py:625-630` — the regex selector keys off `_remote_use_trtexec_safe is not None` (a proxy for "the probe ran") where the comment directly above describes `has_remote_config`, which `binary_name` already uses 10 lines up. Correct today only by an unstated invariant; any future early-return between the probe and this line puts a remote run back on the `Latency` pattern and returns `inf` for everything.
- `autotune/__main__.py:105-118` — the `init_benchmark_instance` call sits above the `try:`, so the newly-raised config errors escape `run_autotune` as a traceback, breaking its documented "1: Autotuning failed" contract and making the `benchmark_instance is None` branch dead for those errors. Failing fast is right; catching and logging keeps it clean.
- Still open from a prior round: `log_file` records only the build output (`benchmark.py:517`), never the remote timing output the latency regex actually parses — so an `inf` candidate is not diagnosable from the saved artifact, which is the main reason the log exists.

**Risk assessment**

**Low-moderate, well-contained.** Everything sits behind `--use_trtexec` in the ONNX autotune path; no `modelopt_state` schema, mode registration, export path, or public `modelopt/torch` API is touched, so there is no checkpoint or restore-fidelity exposure. The `GPU Compute Time` metric switch is now correctly scoped to remote mode, leaving purely local `--use_trtexec` users on `Latency` as before. Residual risk is concentrated in the one IMPORTANT item, which affects dynamic-shape models specifically and is a silent mis-ranking rather than a hard failure.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### dthienan-nv · 2026-09-18 · COMMENTED

(no text)
