# [PR #2451] [6771663] Preserve ONNX API output types when wiring casts

source: https://github.com/NVIDIA/Model-Optimizer/pull/2451
state: closed | updated: 2026-09-22T17:30:04Z
labels: cherry-pick-done, cherry-pick-0.47.0

## 正文

### What does this PR do?

Type of change: Bug fix

Preserves the public ONNX graph I/O types captured at the API boundary when `PrecisionConverter` wires output casts. Type inference can change the working graph's output declaration before conversion; consulting that mutated declaration caused the required cast back to the original public type to be discarded and metadata restoration to fail.

The converter now derives its I/O type map from the preserved boundary metadata and uses that map when deciding whether a cast should become a public graph output. A regression test covers an FP32 output whose working declaration is inferred as FP16, and the changelog records the corrected behavior.

### Usage

```python
# No API changes are required. Existing conversions now preserve the original
# public I/O declarations when keep_io_types=True.
converted = convert_to_f16(model, keep_io_types=True)
```

### Testing

- Ran `pytest tests/unit/onnx/autocast/test_precisionconverter.py` (186 passed).
- Ran `pytest tests/unit/onnx/autocast` (249 passed).
- Ran Ruff check and format validation on the changed Python files.
- Verified the original minimal end-to-end reproduction with Python 3.12 and TensorRT 10.16.1.11; conversion now completes without the output-metadata restoration error.
- Verified the full CLI quantization path proceeds through the formerly failing one-Q/DQ scheme and successfully benchmarks the generated TensorRT engine.

### Before your PR is "*Ready for review*"

Make sure you read and follow [Contributor guidelines](https://github.com/NVIDIA/Model-Optimizer/blob/main/CONTRIBUTING.md) and your commits are signed (`git commit -s -S`).

Make sure you read and follow the [Security Best Practices](https://github.com/NVIDIA/Model-Optimizer/blob/main/SECURITY.md#security-coding-practices-for-contributors) (e.g. avoiding hardcoded `trust_remote_code=True`, `torch.load(..., weights_only=False)`, `pickle`, etc.).

- Is this change backward compatible?: ✅
- If you copied code from any other sources or added a new PIP dependency, did you follow guidance in `CONTRIBUTING.md`: N/A
- Did you write any new necessary tests?: ✅
- Did you update [Changelog](https://github.com/NVIDIA/Model-Optimizer/blob/main/CHANGELOG.rst)?: ✅
- Did you get Claude approval on this PR?: N/A

### Additional Information

Tracking: [6771663]


<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

- **Bug Fixes**
  - Fixed ONNX FP16 conversion to preserve public graph output types when type inference changes internal declarations.
  - Ensured output casts are inserted correctly when preserving input/output types is enabled, maintaining compatibility for downstream consumers.
  - Validated that converted models retain the expected output types and remain compliant with ONNX validation.

- **Tests**
  - Added regression coverage confirming preserved output types, correct cast insertion, and valid ONNX model generation.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

## 评论 (5)

### copy-pr-bot[bot] · 2026-09-16

This pull request requires additional validation before any workflows can run on NVIDIA's runners.

Pull request vetters can view their responsibilities [here](https://docs.gha-runners.nvidia.com/cpr/vetters).

Contributors can view more details about this message [here](https://docs.gha-runners.nvidia.com/cpr/contributors).


### coderabbitai[bot] · 2026-09-16

<!-- This is an auto-generated comment: summarize by coderabbit.ai -->
<!-- review_stack_entry_start -->

<a href="https://app.coderabbit.ai/change-stack/NVIDIA/Model-Optimizer/pull/2451#gh-light-mode-only"><img src="https://storage.googleapis.com/coderabbit_public_assets/review-stack-in-coderabbit-ui.svg" alt="Review Change Stack" width="202" height="32"></a><a href="https://app.coderabbit.ai/change-stack/NVIDIA/Model-Optimizer/pull/2451#gh-dark-mode-only"><img src="https://storage.googleapis.com/coderabbit_public_assets/review-stack-in-coderabbit-ui-dark.svg" alt="Review Change Stack" width="202" height="32"></a>

<!-- review_stack_entry_end -->
<!-- recent_review_start -->

No actionable comments were generated in the recent review. 🎉

<details>
<summary>ℹ️ Recent review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `0101cfcf-d5cf-415b-9729-13ebd139ea8b`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between 5476e662c68b95839c3cca4b1e35b1308c3a82ae and ad24f7fccb2d2e8ffc970d623fa481fedbdfad2e.

</details>

<details>
<summary>📒 Files selected for processing (3)</summary>

* `CHANGELOG.rst`
* `modelopt/onnx/autocast/precisionconverter.py`
* `tests/unit/onnx/autocast/test_precisionconverter.py`

</details>

<details>
<summary>🚧 Files skipped from review as they are similar to previous changes (1)</summary>

* CHANGELOG.rst

</details>

**Included review availability:** Your plan provides up to 12 included reviews per hour; 10 remain after this review.

</details>

---



<!-- recent_review_end -->
<!-- walkthrough_start -->

<details>
<summary>📝 Walkthrough</summary>

## Walkthrough

FP16 conversion now uses preserved API-boundary I/O types when inserting output casts. A regression test verifies that a declared `FLOAT` output remains `FLOAT` and that the converted model passes ONNX validation.

### Changes

**ONNX output type preservation**

|Layer / File(s)|Summary|
|---|---|
|**Preserve API-boundary types** <br> `modelopt/onnx/autocast/precisionconverter.py`|`PrecisionConverter` uses preserved original I/O metadata instead of modified working-model declarations when handling output casts.|
|**Validate output cast behavior** <br> `tests/unit/onnx/autocast/test_precisionconverter.py`, `CHANGELOG.rst`|A regression test checks the declared `FLOAT` output, one output cast, and full ONNX validation. The changelog records the fix.|

<!-- change_assessment_start -->
**Priority:** ⬇️ Low



**Estimated code review effort:** 2 (Simple) | ~10 minutes

<!-- change_assessment_commit:"ad24f7fccb2d2e8ffc970d623fa481fedbdfad2e" -->
**Change:** Bug fix
<!-- change_assessment_end -->

**Suggested reviewers:** `gcunhase`

</details>

<!-- walkthrough_end -->
<!-- final_review_risk_start -->
**Merge Risk:** _⚪ Minimal_ · up to `ad24f`
<!-- final_review_risk_coverage:{"sourceCommitId":"ad24f7fccb2d2e8ffc970d623fa481fedbdfad2e","coveredCommitId":"ad24f7fccb2d2e8ffc970d623fa481fedbdfad2e","kind":"reviewed"} -->

The conversion change preserves declared ONNX output types and includes regression coverage for the reported inference scenario. No unresolved merge-blocking issue remains.
<!-- final_review_risk_end -->
<!-- pre_merge_checks_walkthrough_start -->

<details>
<summary>🚥 Pre-merge checks | ✅ 5 | ❌ 1</summary>

### ❌ Failed checks (1 warning)

|     Check name     | Status     | Explanation                                                                                                                                                                                               | Resolution                                                                         |
| :----------------: | :--------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------- |
| Docstring Coverage | ⚠️ Warning | Docstring coverage is 40.00% which is insufficient. The required threshold is 80.00%. Docstring coverage is scoped to functions touched by this diff. Analyzed 5 functions across 2 files. (1 skipped: 1… | Write docstrings for the functions missing them to satisfy the coverage threshold. |

<details>
<summary>✅ Passed checks (5 passed)</summary>

|         Check name         | Status   | Explanation                                                                                                                                                                                               |
| :------------------------: | :------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|      Description Check     | ✅ Passed | Check skipped - CodeRabbit’s high-level summary is enabled.                                                                                                                                               |
|         Title check        | ✅ Passed | The title clearly and concisely describes the main change: preserving ONNX API output types when inserting casts.                                                                                         |
|     Linked Issues check    | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                                                  |
| Out of Scope Changes check | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                                                  |
|   Security Anti-Patterns   | ✅ Passed | PASS. The authoritative PR diff changes one modelopt Python file, one test file, and CHANGELOG.rst. The added implementation and test lines contain no torch.load(..., weights_only=False), numpy.load(.… |

</details>

<details>
<summary>Full details: Docstring Coverage</summary>

**Explanation**

Docstring coverage is 40.00% which is insufficient. The required threshold is 80.00%. Docstring coverage is scoped to functions touched by this diff. Analyzed 5 functions across 2 files. (1 skipped: 1 unsupported.)

</details>

</details>

<!-- pre_merge_checks_walkthrough_end -->
<!-- finishing_touch_checkbox_start -->

<details>
<summary>✨ Finishing Touches 💡 1</summary>

<!-- finishing_touch_suggestion:docstrings -->
<details>
<summary>📝 Generate docstrings 💡</summary>

- [ ] <!-- {"checkboxId":"7962f53c-55bc-4827-bfbf-6a18da830691"} --> Create stacked PR
- [ ] <!-- {"checkboxId":"3e1879ae-f29b-4d0d-8e06-d12b7ba33d98"} --> Commit on current branch

</details>
<details>
<summary>🧪 Generate unit tests (beta)</summary>

- [ ] <!-- {"checkboxId": "f47ac10b-58cc-4372-a567-0e02b2c3d479", "radioGroupId": "utg-output-choice-group-unknown_comment_id"} -->   Create PR with unit tests
- [ ] <!-- {"checkboxId": "6ba7b810-9dad-11d1-80b4-00c04fd430c8", "radioGroupId": "utg-output-choice-group-unknown_comment_id"} -->   Commit unit tests in branch `ajrasane/nvbug-6771663-triage`

</details>

</details>

<!-- finishing_touch_checkbox_end -->
<!-- tips_start -->

---




<sub>Comment `@coderabbitai help` to get the list of available commands.</sub>

<!-- tips_end -->

### github-actions[bot] · 2026-09-17

[PR Preview Action](https://github.com/rossjrw/pr-preview-action) v1.8.1
:---:
Preview removed because the pull request was closed.
2026-09-18 03:47 UTC
<!-- Sticky Pull Request Commentpr-preview -->

### codecov[bot] · 2026-09-17

## [Codecov](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) Report
:white_check_mark: All modified and coverable lines are covered by tests.
:white_check_mark: Project coverage is 78.83%. Comparing base ([`b9cfdce`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/b9cfdce8dc7f0a358391eee363516fdd9dde55ac?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)) to head ([`aeb0e2c`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/aeb0e2cc8a675785693f881b407c177940ec3205?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)).
:warning: Report is 11 commits behind head on main.

<details><summary>Additional details and impacted files</summary>



```diff
@@            Coverage Diff             @@
##             main    #2451      +/-   ##
==========================================
+ Coverage   71.50%   78.83%   +7.33%     
==========================================
  Files         590      590              
  Lines       64749    64944     +195     
==========================================
+ Hits        46297    51198    +4901     
+ Misses      18452    13746    -4706     
```

| [Flag](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flags&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | Coverage Δ | |
|---|---|---|
| [examples-diffusers](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `20.88% <0.00%> (+<0.01%)` | :arrow_up: |
| [examples-gpt-oss](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.39% <0.00%> (+<0.01%)` | :arrow_up: |
| [examples-hf_ptq](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `22.49% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-llm_distill](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.46% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-llm_eval](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.37% <0.00%> (+<0.01%)` | :arrow_up: |
| [examples-llm_qat](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.67% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-llm_sparsity](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.93% <0.00%> (+<0.01%)` | :arrow_up: |
| [examples-megatron_bridge](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `26.28% <0.00%> (-0.12%)` | :arrow_down: |
| [examples-specdec_bench](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.15% <0.00%> (+<0.01%)` | :arrow_up: |
| [examples-speculative_decoding](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.79% <0.00%> (-0.07%)` | :arrow_down: |
| [examples-torch_onnx](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `21.89% <100.00%> (-0.01%)` | :arrow_down: |
| [examples-torch_trt](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.22% <0.00%> (+<0.01%)` | :arrow_up: |
| [gpu](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `58.36% <100.00%> (+25.91%)` | :arrow_up: |
| [unit](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `57.85% <100.00%> (-0.01%)` | :arrow_down: |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA#carryforward-flags-in-the-pull-request-comment) to find out more.
</details>

[:umbrella: View full report in Codecov by Harness](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2451?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).   
:loudspeaker: Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).
<details><summary> :rocket: New features to boost your workflow: </summary>

- :snowflake: [Test Analytics](https://docs.codecov.com/docs/test-analytics): Detect flaky tests, report on failures, and find test suite problems.
</details>

### ajrasane · 2026-09-18

/ok to test aeb0e2cc8a675785693f881b407c177940ec3205

## Review (2)

### cjluo-nv · 2026-09-17 · APPROVED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Approving: a small, correctly scoped fix that sources `original_network_io` from the boundary metadata instead of the post-inference working declaration, with a regression test and changelog entry.

No action needed.

- Checked the interaction with `_add_cast`'s existing `must_preserve_io_type` guard and `_sanity_check`; both now read the same boundary map, and the fallback when `original_network_io_metadata is None` (i.e. `keep_io_types=False`) reproduces the previous behavior exactly.
- Cast-up/cast-down ordering for an output present in both lists still resolves to the boundary type, which is the intended outcome.

<!-- bot-review sha=5476e662c68b95839c3cca4b1e35b1308c3a82ae -->

### coderabbitai[bot] · 2026-09-17 · APPROVED

(no text)
