# [PR #2432] Fail fast on non-finite AutoQuantize output gradients

source: https://github.com/NVIDIA/Model-Optimizer/pull/2432
state: closed | updated: 2026-09-23T05:32:29Z
labels: cherry-pick-0.47.0

## 正文

### What does this PR do?

Type of change: Bug fix

Fail fast when AutoQuantize receives non-finite output gradients, before accumulating sensitivity scores. The error names the affected module and suggests checking the model, data, and loss; it also identifies cuDNN SDPA backward on fully masked rows as one possible cause and gives an explicit retry workaround.

Unlike the earlier revision, this does not disable cuDNN or change any attention backend settings. Invalid gradients are not zeroed or ignored, and there is no automatic retry.

### Usage

No API or recipe changes. For the reproduced cuDNN failure, the caller can explicitly set `torch.backends.cuda.enable_cudnn_sdp(False)` before a fresh AutoQuantize run.

### Testing

- AutoQuantize unit suite: **110 passed**. Coverage includes NaN and positive/negative infinity, module diagnostics, preventing invalid score accumulation, model-state cleanup, and unchanged SDPA backend settings.
- Real-model E2E on **four GB300 GPUs**, Qwen/Qwen3.6-35B-A3B, main `8025a3dc5481129aa21fef99cb13a879e1b5847e` plus this patch, batch size 8, 512 calibration samples, and `w4a16_nvfp4_fp8_at_6p0bits-active_moe.yaml`:
  - Default backend: the new diagnostic fired at `model.language_model.layers.39.self_attn.q_proj`; cuDNN remained enabled and no quantized model was exported. Expected-error check passed.
  - Explicit cuDNN-disabled fresh run: both 64-batch calibration passes, all 16 scoring batches, optimization at **5.99 effective bits**, and checkpoint export completed with exit code 0. Verified all three indexed safetensors shards and quantization configuration; the index contains 93,563 tensors.
- All applicable pre-commit checks and `git diff --check` passed.

### Before your PR is "*Ready for review*"

Contributor guidelines and security guidance followed; commits are signed and signed off.

- Is this change backward compatible?: Yes; finite-gradient behavior and backend settings are unchanged.
- If you copied code from any other sources or added a new PIP dependency, did you follow guidance in `CONTRIBUTING.md`: N/A; neither added.
- Did you write any new necessary tests?: Yes.
- Did you update [Changelog](https://github.com/NVIDIA/Model-Optimizer/blob/main/CHANGELOG.rst)?: Yes, 0.48.0 bug fixes.
- Did you get Claude approval on this PR?: No; awaiting review.

### Additional Information

This improves error reporting rather than fixing the upstream cuDNN kernel. Blackwell-specificity is not established. Checkpoint deployment/reload was not tested.

A calibration-only checkpoint-resume attempt completed scoring but encountered a separate `candidate_stats` KeyError. That issue is outside this patch; the successful export validation above used a fresh run without search-state resume.


<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **Bug Fixes**
  * AutoQuantize now fails fast when output gradients contain non-finite values, with an actionable error identifying the affected module and troubleshooting guidance.
  * Attention backend settings are preserved and restored after successful runs and failures.
  * Model state is restored when sensitivity scoring encounters an error during setup or execution, including temporary configuration changes.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

## 评论 (4)

### copy-pr-bot[bot] · 2026-09-14

Auto-sync is disabled for draft pull requests in this repository. Workflows must be run manually.

Contributors can view more details about this message [here](https://docs.gha-runners.nvidia.com/cpr/auto-sync).


### coderabbitai[bot] · 2026-09-14

<!-- This is an auto-generated comment: summarize by coderabbit.ai -->
<!-- review_stack_entry_start -->

<a href="https://app.coderabbit.ai/change-stack/NVIDIA/Model-Optimizer/pull/2432#gh-light-mode-only"><img src="https://storage.googleapis.com/coderabbit_public_assets/review-stack-in-coderabbit-ui.svg" alt="Review Change Stack" width="202" height="32"></a><a href="https://app.coderabbit.ai/change-stack/NVIDIA/Model-Optimizer/pull/2432#gh-dark-mode-only"><img src="https://storage.googleapis.com/coderabbit_public_assets/review-stack-in-coderabbit-ui-dark.svg" alt="Review Change Stack" width="202" height="32"></a>

<!-- review_stack_entry_end -->
<!-- recent_review_start -->

No actionable comments were generated in the recent review. 🎉

<details>
<summary>ℹ️ Recent review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `41dff836-c670-4005-9172-2a82756df513`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between 13b0bd65abdf4b7d418fb5dce375dc5ee9914ac3 and e6eca8e69f2a0830015706c0d9761d0902fb620d.

</details>

<details>
<summary>📒 Files selected for processing (3)</summary>

* `CHANGELOG.rst`
* `modelopt/torch/quantization/algorithms.py`
* `tests/unit/torch/quantization/test_autoquant.py`

</details>

<details>
<summary>🚧 Files skipped from review as they are similar to previous changes (1)</summary>

* CHANGELOG.rst

</details>

**Included review availability:** Your plan provides up to 12 included reviews per hour; 11 remain after this review.

</details>

---



<!-- recent_review_end -->
<!-- walkthrough_start -->

<details>
<summary>📝 Walkthrough</summary>

## Walkthrough

AutoQuantize now rejects non-finite output gradients before sensitivity accumulation. Tests verify error handling and restoration of model, scoring, and attention backend state.

### Changes

**AutoQuantize gradient validation**

|Layer / File(s)|Summary|
|---|---|
|**Fail-fast gradient validation** <br> `modelopt/torch/quantization/algorithms.py`|`_accumulate_scores` validates output gradients and raises a module-specific `RuntimeError` when values are non-finite.|
|**Scoring cleanup coverage** <br> `tests/unit/torch/quantization/test_autoquant.py`, `CHANGELOG.rst`|Tests verify state restoration across successful and failed scoring paths, including CUDA SDPA settings. The changelog records the fix.|

<!-- change_assessment_start -->
**Priority:** ⬇️ Low

**Estimated code review effort:** 2 (Simple) | ~10 minutes

<!-- change_assessment_commit:"e6eca8e69f2a0830015706c0d9761d0902fb620d" -->
**Change:** Bug fix
<!-- change_assessment_end -->

</details>

<!-- walkthrough_end -->
<!-- final_review_risk_start -->
**Merge Risk:** _⚪ Minimal_ · up to `e6eca`
<!-- final_review_risk_coverage:{"sourceCommitId":"e6eca8e69f2a0830015706c0d9761d0902fb620d","coveredCommitId":"e6eca8e69f2a0830015706c0d9761d0902fb620d","kind":"reviewed"} -->

The change has no identified merge-blocking risk.
<!-- final_review_risk_end -->
<!-- pre_merge_checks_walkthrough_start -->

<details>
<summary>🚥 Pre-merge checks | ✅ 5 | ❌ 1</summary>

### ❌ Failed checks (1 warning)

|     Check name     | Status     | Explanation                                                                                                                                                                                               | Resolution                                                                         |
| :----------------: | :--------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------- |
| Docstring Coverage | ⚠️ Warning | Docstring coverage is 16.67% which is insufficient. The required threshold is 80.00%. Docstring coverage is scoped to functions touched by this diff. Analyzed 6 functions across 2 files. (1 skipped: 1… | Write docstrings for the functions missing them to satisfy the coverage threshold. |

<details>
<summary>✅ Passed checks (5 passed)</summary>

|         Check name         | Status   | Explanation                                                                                                                                                                                               |
| :------------------------: | :------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|      Description Check     | ✅ Passed | Check skipped - CodeRabbit’s high-level summary is enabled.                                                                                                                                               |
|         Title check        | ✅ Passed | The title clearly and concisely describes the main change: AutoQuantize now fails fast when output gradients are non-finite.                                                                              |
|     Linked Issues check    | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                                                  |
| Out of Scope Changes check | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                                                  |
|   Security Anti-Patterns   | ✅ Passed | PASS. The reviewed range changes one package Python file, `modelopt/torch/quantization/algorithms.py`, and adds only a `torch.isfinite` check plus diagnostic error text. The added code does not use `t… |

</details>

<details>
<summary>Full details: Docstring Coverage</summary>

**Explanation**

Docstring coverage is 16.67% which is insufficient. The required threshold is 80.00%. Docstring coverage is scoped to functions touched by this diff. Analyzed 6 functions across 2 files. (1 skipped: 1 unsupported.)

</details>

</details>

<!-- pre_merge_checks_walkthrough_end -->

- [ ] <!-- {"checkboxId":"585bb3f6-faf5-4dbf-96d2-74e382adf19a"} --> Fix all pre-merge checks with AI
<!-- finishing_touch_checkbox_start -->

<details>
<summary>✨ Finishing Touches 💡 1</summary>

<!-- finishing_touch_suggestion:docstrings -->
<details>
<summary>📝 Generate docstrings 💡</summary>

- [ ] <!-- {"checkboxId":"7962f53c-55bc-4827-bfbf-6a18da830691"} --> Create stacked PR
- [ ] <!-- {"checkboxId":"3e1879ae-f29b-4d0d-8e06-d12b7ba33d98"} --> Commit on current branch

</details>
<details>
<summary>🧪 Generate unit tests (beta)</summary>

- [ ] <!-- {"checkboxId": "6ba7b810-9dad-11d1-80b4-00c04fd430c8", "radioGroupId": "utg-output-choice-group-unknown_comment_id"} --> Commit to this branch
- [ ] <!-- {"checkboxId": "f47ac10b-58cc-4372-a567-0e02b2c3d479", "radioGroupId": "utg-output-choice-group-unknown_comment_id"} --> Create a new PR

</details>

</details>

<!-- finishing_touch_checkbox_end -->
<!-- tips_start -->

---




<sub>Comment `@coderabbitai help` to get the list of available commands.</sub>

<!-- tips_end -->

### github-actions[bot] · 2026-09-14

[PR Preview Action](https://github.com/rossjrw/pr-preview-action) v1.8.1
:---:
Preview removed because the pull request was closed.
2026-09-17 17:53 UTC
<!-- Sticky Pull Request Commentpr-preview -->

### codecov[bot] · 2026-09-14

## [Codecov](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) Report
:white_check_mark: All modified and coverable lines are covered by tests.
:white_check_mark: Project coverage is 78.97%. Comparing base ([`b9cfdce`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/b9cfdce8dc7f0a358391eee363516fdd9dde55ac?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)) to head ([`e6eca8e`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/e6eca8e69f2a0830015706c0d9761d0902fb620d?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)).

<details><summary>Additional details and impacted files</summary>



```diff
@@            Coverage Diff             @@
##             main    #2432      +/-   ##
==========================================
+ Coverage   71.50%   78.97%   +7.47%     
==========================================
  Files         590      590              
  Lines       64749    64750       +1     
==========================================
+ Hits        46297    51136    +4839     
+ Misses      18452    13614    -4838     
```

| [Flag](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flags&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | Coverage Δ | |
|---|---|---|
| [examples-diffusers](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `20.88% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-gpt-oss](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.39% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-hf_ptq](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `22.49% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-llm_distill](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.46% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-llm_eval](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.37% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-llm_qat](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.67% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-llm_sparsity](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.93% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-megatron_bridge](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `26.27% <0.00%> (-0.12%)` | :arrow_down: |
| [examples-specdec_bench](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.15% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-speculative_decoding](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.79% <0.00%> (-0.07%)` | :arrow_down: |
| [examples-torch_onnx](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `21.89% <0.00%> (-0.01%)` | :arrow_down: |
| [examples-torch_trt](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.22% <0.00%> (-0.01%)` | :arrow_down: |
| [gpu](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `58.35% <0.00%> (+25.91%)` | :arrow_up: |
| [regression](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.15% <0.00%> (+0.29%)` | :arrow_up: |
| [unit](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `57.86% <100.00%> (+<0.01%)` | :arrow_up: |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA#carryforward-flags-in-the-pull-request-comment) to find out more.
</details>

[:umbrella: View full report in Codecov by Harness](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2432?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).   
:loudspeaker: Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).
<details><summary> :rocket: New features to boost your workflow: </summary>

- :snowflake: [Test Analytics](https://docs.codecov.com/docs/test-analytics): Detect flaky tests, report on failures, and find test suite problems.
</details>

## Review (3)

### cjluo-nv · 2026-09-17 · COMMENTED

> _Bot review (gpt-5.6-sol) — DM the bot to share feedback._

LGTM: the fail-fast check is scoped correctly, restores session state, preserves backend settings, and has focused non-finite-gradient coverage.

Needs action:
- [ ] Provide human sign-off for the justified edit to `test_backward_scoring_session_restores_partial_setup`, which adds coverage that failure cleanup leaves cuDNN SDPA unchanged.

<!-- bot-review sha=3f5947ecec656015dad1828ddffdb8d0eee08a73 -->

### coderabbitai[bot] · 2026-09-17 · APPROVED

(no text)

### cjluo-nv · 2026-09-17 · APPROVED

> _Bot review (gpt-5.6-sol) — DM the bot to share feedback._

Approved: the fail-fast check is scoped correctly, preserves scoring cleanup, and has focused NaN and infinity coverage.
No action needed:
- :heavy_check_mark: The prior sign-off request is no longer applicable: `test_backward_scoring_session_restores_partial_setup` remains unchanged; this PR only inserts new tests before it.

<!-- bot-review sha=13b0bd65abdf4b7d418fb5dce375dc5ee9914ac3 -->
