# [PR #2415] [6721556] Fix mixed-dtype NVFP4 ONNX precision conversion

source: https://github.com/NVIDIA/Model-Optimizer/pull/2415
state: open | updated: 2026-09-23T21:48:55Z
labels: 

## 正文

### What does this PR do?

Type of change: Bug fix with an intentional numerical-policy change

NVFP4 ONNX export could send mixed FP32/FP16 operations to TensorRT before precision conversion, causing Swin export to fail at an `Add`. This PR normalizes compute dtypes before parsing and supports FP32, BF16, and mixed FP32/BF16 sources exported to FP16 or BF16, including NVFP4 models with accompanying FP8 layers. Known output-boundary limitations are listed below; this is not a general AutoCast boundary rewrite.

- Uses one Q/DQ-aware AutoCast conversion path for supported NVFP4 conversions. Native BF16→BF16 remains a weight-focused no-op. Pure FP8 and models combining NVFP4 with INT4, INT8, or MXFP8 retain their previous routing and validation.
- Declares dynamic NVFP4 outputs as FP4 data and FP8 scales even when intermediate shapes are unknown. The NVFP4 deployment caller explicitly opts into deferred TensorRT inference until compute dtypes are normalized. Other callers retain inference, even with the same plugin; bypass still requires the exact plugin/output signature.
- Selects compute precision per quantized weight, aligns `MatMul`/`Gemm` operands and optional bias, preserves FP32 boundaries with Casts, and ensures the required Q/DQ opset.
- Handles BF16 dtype enums and Cast shape propagation in shared AutoCast. Fixes a shared initializer-conversion bug that changed sufficiently tiny negative values to positive values.

**Numerical compatibility:** NVFP4 exports previously using the legacy FP16 converter now adopt AutoCast's policies. This can change arithmetic precision (for example, `Div` may run in FP16) and constant values: FP16 bounds are ±65,504 rather than ±10,000, infinities are clamped to finite bounds, and tiny nonzero magnitudes are raised to the smallest FP16 subnormal with their sign preserved. Revalidate model accuracy; this is not claimed to be numerically equivalent to the legacy route.

### Usage

```python
# model is NVFP4-quantized; accompanying FP8 layers are supported.
from modelopt.torch._deploy.utils import get_onnx_bytes_and_metadata

onnx_bytes, metadata = get_onnx_bytes_and_metadata(
    model, (sample_input,), weights_dtype="bf16"  # or "fp16"
)
```

The deployment path sets `keep_io_types=False` and enables the NVFP4-specific opt-in internally. Ordinary `convert_to_f16` callers retain the default `defer_nvfp4_trt_inference=False`; any caller explicitly opting in must validate the converted graph in TensorRT.

### Testing

Latest CPU validation covers [03b814c1a9a85bcaa60c4135ee1e48c30c853202](https://github.com/NVIDIA/Model-Optimizer/commit/03b814c1a9a85bcaa60c4135ee1e48c30c853202). Its committed source tree, `ede0f480cd9dca8d57d8db4361a4ef68c439ac90`, exactly matches the tested tree. This follows merge commit `794aa396ce7d782f0e79a58e652372c40cf792f6`, incorporating `main` at `25d8c91762e2111f57f8e760a3a42d6c4d929e8f`.

```bash
CUDA_VISIBLE_DEVICES="" python -m pytest -o addopts= -p no:cacheprovider -q \
  tests/unit/torch/deploy/utils/test_torch_onnx_utils.py \
  tests/unit/torch/quantization/test_onnx_export_cpu.py \
  tests/unit/onnx/test_fold_casts.py \
  tests/unit/onnx/quantization/test_qdq_utils.py \
  tests/unit/onnx/autocast/test_precisionconverter.py \
  tests/unit/onnx/autocast/test_graphsanitizer.py \
  tests/unit/torch/quantization/test_tensor_quantizer_cpu.py
```

Result: **409 passed in 17.57 seconds**. The focused review-follow-up suite also passed **32 tests in 2.10 seconds**.

- CPU tests exercise real export/conversion with a CPU stand-in only for the CUDA dynamic-calibration kernel. Original supported conversion, native BF16 no-op, FP8 coexistence, Gemm bias, LayerNorm/elementwise, and unrelated-format routing coverage remains.
- All six original single-output mixed-precision cases retain their payload dtype/dimension/byte checks, Add operand agreement, FP8 scales, and dynamic batch assertions. A separate NVFP4 `weights_dtype="fp32"` test verifies native BF16 and explicitly FP32-cast graph outputs against eager dtypes, including direct weighted-node/Cast wiring.
- Tests verify default versus opted-in plugin inference, including missing shapes, incorrect/missing types, and additional custom operators. Public FP16→BF16 conversion with `keep_io_types=False` checks both inference modes, BF16 input/output declarations, initializer values, names/shapes, no boundary Casts, and full ONNX validity.
- Public AutoCast tests continue to verify large/tiny constants, negative underflow, signed zero, infinity, and NaN. Before the sign-preservation fix, both inference modes failed specifically on tiny negative values.
- Relevant-file and commit hooks passed, including Ruff, mypy, license, and Bandit. Markdown lint was skipped; this follow-up changes Python files only.

**Blackwell validation: 13/13 PASS with explicit TensorRT builder optimization level 0. Default level 3 remains FAILED for the three Swin runtime cases; no waiver is taken.** Both runs tested current head `03b814c1a9a85bcaa60c4135ee1e48c30c853202`, tree `ede0f480cd9dca8d57d8db4361a4ef68c439ac90`, on 2026-09-23. No production code, quantization inputs, graph precision, or finite-output assertions were changed for the level-0 run.

Environment: one NVIDIA B200 (SM 10.0), driver 615.71.09, `nvcr.io/nvidia/pytorch:26.07-py3` pinned to `sha256:2140e699b3beaf7f96a0081fd9c9406bc3832b435cdb60dfa2d261f7d2f34a1c`; CUDA 13.3, TensorRT 11.1.0.106, PyTorch `2.13.0a0+9186a08b2c.nv26.07`, ONNX 1.21.0, and timm 1.0.29. Each run used one non-exclusive B200 with a one-hour allocation; the repository was editable-installed and its import path verified in that run's container. The level-0 job completed with scheduler and harness exit code 0.

| Cases | Default level 3 | Explicit level 0 |
| --- | --- | --- |
| Nine small-model conversion/FP8-hybrid cases | 9/9 PASS | 9/9 PASS |
| Native BF16 + explicit FP32 graph-output boundary | PASS | PASS |
| Reduced Swin FP32→FP16 | FAIL: nonfinite runtime output | PASS |
| Reduced Swin FP32→BF16 | FAIL: nonfinite runtime output | PASS |
| Reduced Swin BF16→FP16 | FAIL: nonfinite runtime output | PASS |

The nine small-model cases cover FP32→FP16 with/without accompanying FP8, FP32→BF16, BF16→FP16, BF16→BF16, and mixed→FP16/BF16 with/without FP8. The boundary case uses `weights_dtype="fp32"` and verifies eager/exported/runtime output dtypes `[FP32, BF16, FP32]`, including direct weighted-node and explicit Cast wiring. Each Swin case uses random weights, depths `[1,1,1,1]`, input shape `[1,3,224,224]`, and output shape `[1,1000]`.

Every level-0 case used real CUDA quantization with seed 42 and fresh ONNX exports, full ONNX checking, mandatory TensorRT 11 strong typing, a 4-GiB workspace limit, engine serialization and reload, one warmup plus three measured executions, exact runtime shape/dtype and linear-layout/stride checks, and finite-output assertions. No previously exported graph or engine was reused. Source fingerprints matched before/after; all 26 ONNX/engine artifact hashes were independently checked.

Ten small/boundary ONNX exports match the default-level run byte-for-byte. The three fresh Swin exports differ only in `value_info` ordering; their complete protobufs are identical after sorting that metadata. Nodes, initializers, scales, input/output contracts, and other metadata are unchanged.

The isolated captured-activation Swin tails pass at default level 3, while the unchanged full BF16 graph passes at level 0. Promoting only dynamic-quantizer global scales to FP32 did not fix the full default-level graph. This establishes optimization-context sensitivity, not a proven specific TensorRT root cause. **The default-level Swin failures remain unresolved and must not be described as passing or waived.**

The passing run explicitly set:

```python
config.builder_optimization_level = 0
```

External validation-harness invocation (harness/logs/artifacts kept outside the repository):

```bash
python -m pip install --no-deps --no-build-isolation -e .
python /path/to/validate_blackwell.py \
  --repo "$PWD" --output-dir /path/to/fresh-results \
  --expected-head 03b814c1a9a85bcaa60c4135ee1e48c30c853202 \
  --expected-tree ede0f480cd9dca8d57d8db4361a4ef68c439ac90 \
  --builder-optimization-level 0
```

Evidence SHA256: harness `89b038eef8c5d66102e500d184f72485fe0dbbb11ba8fa45ef189e7c76c8ac94`; completed manifest `27707bc62cfb5b0618c55164eaee86508a571afb5d198200f3ad470fa4875180`; completed job log `11f0f2b0231d1a00d4b8b4c1fe42e4721e49461a0bc3eb30aa0156f298cd9543`. The associated validation reply lists per-case ONNX and engine hashes. These are synthetic build/runtime smoke checks, not pretrained-model accuracy or performance validation.

### Before your PR is "*Ready for review*"

Make sure you read and follow [Contributor guidelines](https://github.com/NVIDIA/Model-Optimizer/blob/main/CONTRIBUTING.md) and sign your commits (`git commit -s -S`). Follow the [Security Best Practices](https://github.com/NVIDIA/Model-Optimizer/blob/main/SECURITY.md#security-coding-practices-for-contributors).

- Is this change backward compatible?: ❌ Not numerically equivalent to the previous NVFP4 FP16 route; existing public calls and source/target routing are preserved, subject to the known boundary limitations below. The intentional precision-policy change is documented in CHANGELOG.
- If you copied code from any other sources or added a new PIP dependency, did you follow guidance in `CONTRIBUTING.md`: N/A
- Did you write any new necessary tests?: ✅
- Did you update [Changelog](https://github.com/NVIDIA/Model-Optimizer/blob/main/CHANGELOG.rst)?: ✅
- Did you get Claude approval on this PR?: ❌

### Additional Information

`weights_dtype="fp32"` preserves existing public boundaries around low-precision NVFP4 compute; it does not request a general BF16→FP32 conversion. `TRT_FP4QDQ` may leave stale FLOAT metadata on native-BF16 weighted outputs; those declarations are corrected per weight, while actual FP32 boundaries remain explicit Casts.

This follow-up stays specific to the original NVFP4 mixed-dtype bug. Broader experiments exposed separate FP16→BF16 `keep_io_types=True` output-preservation and aliased multi-output conversion/shape-cleanup failures. They remain unresolved and outside this patch; they are not marked passing or xfailed in the committed suite. NVFP4 deployment uses `keep_io_types=False`. All original mixed-precision regression cases remain intact. No extra changelog entry was added for narrowing the inference bypass introduced within this same unreleased PR.

Dynamic-shape metadata limitations in the unchanged FP32-preserving path were also reproduced on the prior head. The existing static FP32 cases remain, and dynamic-shape assertions cover the FP16/BF16 conversion targets.

Human review remains required; signed commits do not constitute human approval. The level-0 Blackwell pass does not waive the unresolved default-level Swin failures or constitute maintainer acceptance. No review threads are resolved by this update.

> 🤖 _Generated by Codex (AI agent)._


## 评论 (9)

### copy-pr-bot[bot] · 2026-09-11

Auto-sync is disabled for draft pull requests in this repository. Workflows must be run manually.

Contributors can view more details about this message [here](https://docs.gha-runners.nvidia.com/cpr/auto-sync).


### coderabbitai[bot] · 2026-09-11

<!-- This is an auto-generated comment: summarize by coderabbit.ai -->
<!-- review_stack_entry_start -->

<a href="https://app.coderabbit.ai/change-stack/NVIDIA/Model-Optimizer/pull/2415#gh-light-mode-only"><img src="https://storage.googleapis.com/coderabbit_public_assets/review-stack-in-coderabbit-ui.svg" alt="Review Change Stack" width="202" height="32"></a><a href="https://app.coderabbit.ai/change-stack/NVIDIA/Model-Optimizer/pull/2415#gh-dark-mode-only"><img src="https://storage.googleapis.com/coderabbit_public_assets/review-stack-in-coderabbit-ui-dark.svg" alt="Review Change Stack" width="202" height="32"></a>

<!-- review_stack_entry_end -->
<!-- This is an auto-generated comment: review paused by coderabbit.ai -->

> [!NOTE]
> ## Reviews paused
> 
> It looks like this branch is under active development. To avoid overwhelming you with review comments due to an influx of new commits, CodeRabbit has automatically paused this review. You can configure this behavior by changing the `reviews.auto_review.auto_pause_after_reviewed_commits` setting.
> 
> Use the following commands to manage reviews:
> - `@coderabbitai resume` to resume automatic reviews.
> - `@coderabbitai review` to trigger a single review.
> 
> Use the checkboxes below for quick actions:
> - [ ] <!-- {"checkboxId":"7f6cc2e2-2e4e-497a-8c31-c9e4573e93d1"} --> ▶️ Resume reviews
> - [ ] <!-- {"checkboxId":"e9bb8d72-00e8-4f67-9cb2-caf3b22574fe"} --> 🔍 Trigger review

<!-- end of auto-generated comment: review paused by coderabbit.ai -->
<!-- recent_review_start -->

No actionable comments were generated in the recent review. 🎉

<details>
<summary>ℹ️ Recent review info</summary>

<details>
<summary>⚙️ Run configuration</summary>

**Configuration used**: Path: .coderabbit.yaml

**Review profile**: CHILL

**Plan**: Enterprise

**Run ID**: `2f0ba5a5-0fde-4549-ba6c-7a7f0ac6db45`

</details>

<details>
<summary>📥 Commits</summary>

Reviewing files that changed from the base of the PR and between 7038eb84d646cbeecdf14806d3074fc7e97b4786 and 7a2d3ed47a58fbe724e0d98d8b6e46b93a1f6b82.

</details>

<details>
<summary>📒 Files selected for processing (1)</summary>

* `CHANGELOG.rst`

</details>

**Included review availability:** Your plan provides up to 12 included reviews per hour; 10 remain after this review.

</details>

---



<!-- recent_review_end -->
<!-- walkthrough_start -->

<details>
<summary>📝 Walkthrough</summary>

## Walkthrough

The change updates NVFP4 and FP8 ONNX precision handling. It adds FP4 graph opset normalization, preserves compatible BF16 paths, aligns casted output types, and adds regression tests for conversion errors and mixed-precision graphs.

### Changes

**ONNX precision conversion and NVFP4 export**

|Layer / File(s)|Summary|
|---|---|
|**Conversion validation and export handling** <br> `modelopt/torch/_deploy/utils/torch_onnx.py`|FP4 and FP8 graphs support BF16 no-op handling, reject unsupported conversions, and normalize FP4 graphs to the required opset.|
|**NVFP4 graph casting** <br> `modelopt/onnx/export/nvfp4_exporter.py`|The exporter casts Gemm inputs to the selected precision and restores original output types when required.|
|**NVFP4 regression coverage** <br> `tests/unit/torch/deploy/utils/test_torch_onnx_utils.py`, `tests/unit/torch/quantization/test_onnx_export_cpu.py`, `CHANGELOG.rst`|Tests cover conversion errors, converter selection, BF16 preservation, ONNX validity, and consistent elementwise and Gemm dtypes. The changelog records the mixed-precision NVFP4 export fix.|

<!-- change_assessment_start -->
**Priority:** ➖ Normal





















**Estimated code review effort:** 3 (Moderate) | ~20 minutes

<!-- change_assessment_commit:"7a2d3ed47a58fbe724e0d98d8b6e46b93a1f6b82" -->
**Change:** Bug fix
<!-- change_assessment_end -->

**Suggested reviewers:** `edwardf0t1`

</details>

<!-- walkthrough_end -->
<!-- final_review_risk_start -->
**Merge Risk:** _⚪ Minimal_ · up to `7a2d3`
<!-- final_review_risk_coverage:{"sourceCommitId":"7a2d3ed47a58fbe724e0d98d8b6e46b93a1f6b82","coveredCommitId":"7a2d3ed47a58fbe724e0d98d8b6e46b93a1f6b82","kind":"reviewed"} -->

Supported NVFP4 paths normalize opsets, reject unsupported conversions, and preserve the tested precision boundaries.
<!-- final_review_risk_end -->
<!-- pre_merge_checks_walkthrough_start -->

<details>
<summary>🚥 Pre-merge checks | ✅ 5 | ❌ 1</summary>

### ❌ Failed checks (1 warning)

|     Check name     | Status     | Explanation                                                                                                                                                                                               | Resolution                                                                         |
| :----------------: | :--------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | :--------------------------------------------------------------------------------- |
| Docstring Coverage | ⚠️ Warning | Docstring coverage is 9.09% which is insufficient. The required threshold is 80.00%. Docstring coverage is scoped to functions touched by this diff. Analyzed 22 functions across 4 files. (1 skipped: 1… | Write docstrings for the functions missing them to satisfy the coverage threshold. |

<details>
<summary>✅ Passed checks (5 passed)</summary>

|         Check name         | Status   | Explanation                                                                                                                                                                                               |
| :------------------------: | :------- | :-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
|     Linked Issues check    | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                                                  |
| Out of Scope Changes check | ✅ Passed | Check skipped because no linked issues were found for this pull request.                                                                                                                                  |
|   Security Anti-Patterns   | ✅ Passed | PASS. The PR changes only two modelopt Python files and no examples or dependency manifests. The added-line scan found no torch.load(..., weights_only=False), unsafe NumPy loading, hardcoded trust_rem… |
|      Description Check     | ✅ Passed | Check skipped - CodeRabbit’s high-level summary is enabled.                                                                                                                                               |
|         Title check        | ✅ Passed | The title clearly and concisely describes the main change: fixing mixed-dtype precision conversion for NVFP4 ONNX exports.                                                                                |

</details>

<details>
<summary>Full details: Docstring Coverage</summary>

**Explanation**

Docstring coverage is 9.09% which is insufficient. The required threshold is 80.00%. Docstring coverage is scoped to functions touched by this diff. Analyzed 22 functions across 4 files. (1 skipped: 1 unsupported.)

</details>

</details>

<!-- pre_merge_checks_walkthrough_end -->

- [ ] <!-- {"checkboxId":"585bb3f6-faf5-4dbf-96d2-74e382adf19a"} --> Fix all pre-merge checks with AI
<!-- finishing_touch_checkbox_start -->

<details>
<summary>✨ Finishing Touches</summary>

<details open>
<summary>🧪 Generate unit tests (beta)</summary>

- [ ] <!-- {"checkboxId": "6ba7b810-9dad-11d1-80b4-00c04fd430c8", "radioGroupId": "utg-output-choice-group-unknown_comment_id"} --> Commit to this branch
- [ ] <!-- {"checkboxId": "f47ac10b-58cc-4372-a567-0e02b2c3d479", "radioGroupId": "utg-output-choice-group-unknown_comment_id"} --> Create a new PR

</details>

</details>

<!-- finishing_touch_checkbox_end -->
<!-- tips_start -->

---




<sub>Comment `@coderabbitai help` to get the list of available commands.</sub>

<!-- tips_end -->

### github-actions[bot] · 2026-09-11

[PR Preview Action](https://github.com/rossjrw/pr-preview-action) v1.8.1
:---:
| <p><img src="https://qr.rossjrw.com/?color.dark=0d1117&url=https://NVIDIA.github.io/Model-Optimizer/pr-preview/pr-2415/" height="100" align="right" alt="QR code for preview link"></p> :rocket: View preview at <br> https://NVIDIA.github.io/Model-Optimizer/pr-preview/pr-2415/ <br><br>
| <h6>Built to branch [`gh-pages`](https://github.com/NVIDIA/Model-Optimizer/tree/gh-pages) at 2026-09-23 20:01 UTC. <br> Preview will be ready when the [GitHub Pages deployment](https://github.com/NVIDIA/Model-Optimizer/deployments) is complete. <br><br> </h6>
<!-- Sticky Pull Request Commentpr-preview -->

### codecov[bot] · 2026-09-11

## [Codecov](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415?dropdown=coverage&src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) Report
:x: Patch coverage is `98.88889%` with `1 line` in your changes missing coverage. Please review.
:white_check_mark: Project coverage is 78.35%. Comparing base ([`87f7d14`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/87f7d1432f6dccffe67069c84b9a18877a35019d?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)) to head ([`03b814c`](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/commit/03b814c1a9a85bcaa60c4135ee1e48c30c853202?dropdown=coverage&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA)).
:warning: Report is 4 commits behind head on main.

| [Files with missing lines](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415?dropdown=coverage&src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | Patch % | Lines |
|---|---|---|
| [modelopt/onnx/export/nvfp4\_exporter.py](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415?src=pr&el=tree&filepath=modelopt%2Fonnx%2Fexport%2Fnvfp4_exporter.py&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA#diff-bW9kZWxvcHQvb25ueC9leHBvcnQvbnZmcDRfZXhwb3J0ZXIucHk=) | 98.24% | [1 Missing :warning: ](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) |

<details><summary>Additional details and impacted files</summary>



```diff
@@            Coverage Diff             @@
##             main    #2415      +/-   ##
==========================================
+ Coverage   68.82%   78.35%   +9.53%     
==========================================
  Files         604      605       +1     
  Lines       66858    68222    +1364     
==========================================
+ Hits        46013    53456    +7443     
+ Misses      20845    14766    -6079     
```

| [Flag](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flags&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | Coverage Δ | |
|---|---|---|
| [examples-diffusers](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `21.39% <40.00%> (-0.02%)` | :arrow_down: |
| [examples-gpt-oss](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.43% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-hf_ptq](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `22.80% <0.00%> (-0.09%)` | :arrow_down: |
| [examples-llm_distill](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.50% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-llm_eval](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.41% <0.00%> (-0.05%)` | :arrow_down: |
| [examples-llm_qat](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.70% <0.00%> (-0.05%)` | :arrow_down: |
| [examples-llm_sparsity](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.94% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-megatron_bridge](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `26.10% <0.00%> (-0.18%)` | :arrow_down: |
| [examples-specdec_bench](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.19% <0.00%> (-0.03%)` | :arrow_down: |
| [examples-speculative_decoding](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `17.78% <0.00%> (-0.09%)` | :arrow_down: |
| [examples-torch_onnx](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `21.96% <93.33%> (+0.01%)` | :arrow_up: |
| [examples-torch_trt](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.27% <0.00%> (-0.04%)` | :arrow_down: |
| [examples-vllm_serve](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `13.84% <0.00%> (-0.04%)` | :arrow_down: |
| [gpu](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `58.76% <73.33%> (+37.17%)` | :arrow_up: |
| [regression](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `15.15% <0.00%> (+0.11%)` | :arrow_up: |
| [unit](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415/flags?src=pr&el=flag&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA) | `58.56% <97.77%> (+0.25%)` | :arrow_up: |

Flags with carried forward coverage won't be shown. [Click here](https://docs.codecov.io/docs/carryforward-flags?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA#carryforward-flags-in-the-pull-request-comment) to find out more.
</details>

[:umbrella: View full report in Codecov by Harness](https://app.codecov.io/gh/NVIDIA/Model-Optimizer/pull/2415?dropdown=coverage&src=pr&el=continue&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).   
:loudspeaker: Have feedback on the report? [Share it here](https://about.codecov.io/codecov-pr-comment-feedback/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=NVIDIA).
<details><summary> :rocket: New features to boost your workflow: </summary>

- :snowflake: [Test Analytics](https://docs.codecov.com/docs/test-analytics): Detect flaky tests, report on failures, and find test suite problems.
</details>

### ajrasane · 2026-09-11

@cjluo-nv Addressed the three review items in `1ffc34f89`:

- Opset: NVFP4 Q/DQ precision requirements are now derived after weight post-processing, and the graph is upgraded to opset 23 before precision conversion without invoking TensorRT custom-node discovery.
- End-to-end coverage: added a real CPU NVFP4 MatMul→Add export regression. It retains dynamic FP4 activation quantization, passes full ONNX checking and strict shape inference, and asserts that every elementwise node has consistent floating input types.
- BF16: pure native-BF16 NVFP4 export is now an explicit weight-focused no-op, so it does not enter AutoCast/TensorRT pre-parsing. FP32-to-BF16 and BF16-to-FP16 NVFP4 conversions fail early. The exporter also keeps MatMul/Gemm output annotations consistent with its inserted BF16/FP16 casts.

Validation: 128 affected CPU tests passed; the public Swin NVFP4 reproducer exported an opset-23 graph with zero mixed floating-type elementwise operations and completed a strongly typed TensorRT 11.1 engine build on Blackwell.

> 🤖 _Generated by Codex (AI agent)._


### ajrasane · 2026-09-12

Addressed the current-head review items in `c97ae4a5d` and merged the latest `main` in `2b8c579cb`:

- Expanded the changelog and corrected the PR compatibility declaration to document the new FP32-to-BF16 and BF16-to-FP16 `ValueError` behavior.
- Fixed the accepted `weights_dtype="fp32"` path: NVFP4 `MatMul`/`Gemm` operations stay in their supported low-precision compute type, an optional `Gemm` bias is cast to that type, and an explicit output cast restores the FP32 graph boundary.
- Added real CPU NVFP4 coverage for both `MatMul` plus bias `Add` and biased `Gemm`, parameterized across FP32 preservation, FP32-to-FP16 conversion, and native-BF16 no-op behavior. The graphs retain dynamic FP4 activation quantization, use opset 23, and pass full ONNX checking and strict shape inference.
- Reran 20 focused CPU cases after the base merge; all passed. Changed-file hooks also passed.

The PR is now conflict-free. Current-head Blackwell/TensorRT acceptance has not been rerun, and human approval remains external.

> 🤖 _Generated by Codex (AI agent)._


### ajrasane · 2026-09-18

@cjluo-nv Addressed the current-head review items in `7038eb84d`:

- BF16: the re-stamp is required for native-BF16 because `TRT_FP4QDQ` lacks shape inference and leaves MatMul/Gemm outputs annotated FLOAT; true FP32 boundaries are already explicit Casts. The actual bug was global precision inference: any BF16 initializer could retype unrelated FP32 branches. Precision is now derived per quantized weight, with an inline comment documenting the invariant.
- Regression: added a real mixed FP32/BF16 NVFP4 export test. It failed before the fix with `Add ... B has inconsistent type tensor(float)` and now passes full ONNX checking and strict shape inference with both Add inputs FLOAT.
- Validation: the formatter-final affected suite passed (`133 passed`); all changed-file hooks passed.
- Blackwell: current-head engine-build acceptance is explicitly waived because the available a9 host currently exposes only RTX 6000 Ada (SM89), with no B100/B200/SM120 device. The earlier SM120 TensorRT 11.1 pass was pre-current-head and is not counted as current validation. The PR description now records the waiver and evidence boundary.

Human approval remains external.

> 🤖 _Generated by Codex (AI agent)._


### ajrasane · 2026-09-23

Follow-up to [the review](https://github.com/NVIDIA/Model-Optimizer/pull/2415#pullrequestreview-5294682098), implemented in [03b814c1a](https://github.com/NVIDIA/Model-Optimizer/commit/03b814c1a9a85bcaa60c4135ee1e48c30c853202):

1. **BF16 graph outputs:** Added NVFP4 coverage under `weights_dtype="fp32"` for outputs `[FP32, BF16, FP32]`, matching eager execution. The native BF16 output comes directly from the weighted node and the explicitly FP32 output retains its Cast. All six existing single-output mixed-precision cases and their payload/dynamic-shape assertions remain intact.

2. **Inference deferral:** Added default-off `defer_nvfp4_trt_inference`, enabled by the supported NVFP4 deployment caller and forwarded through both sanitization passes. Bypass still requires the exact plugin/output signature. Encountering that plugin alone no longer changes ordinary AutoCast callers' inference behavior. Default, opted-in, missing-shape, invalid-type, and additional-custom-op cases are covered.

3. **FP16→BF16 interface:** Public `convert_to_f16` coverage now verifies `keep_io_types=False` in both inference modes: BF16 I/O, initializer values, names/shapes, wiring, no boundary Casts, and full ONNX validity. The additional `keep_io_types=True` experiment exposed a separate preservation failure; converting aliased multiple outputs also exposed cleanup/shape failures. Those general fixes are deliberately outside this original NVFP4 bug fix and remain unresolved, not waived or marked passing.

4. **Validation and approval:** This commit's tree exactly matches the tree that passed **32 focused tests**, the **409-test seven-file CPU suite**, and relevant hooks. Eight B200 build/serialize/reload/runtime checks passed on an earlier staged tree; they do **not** validate this commit. The corrected full-matrix retry failed during setup before executing cases, so current-head Blackwell validation remains incomplete. These are synthetic smoke checks, not pretrained-model accuracy validation. No waiver or human maintainer sign-off is claimed; review threads remain unresolved.

> 🤖 _Generated by Codex (AI agent)._


### ajrasane · 2026-09-23

Blackwell validation update for [03b814c](https://github.com/NVIDIA/Model-Optimizer/commit/03b814c1a9a85bcaa60c4135ee1e48c30c853202), following [the existing review](https://github.com/NVIDIA/Model-Optimizer/pull/2415#pullrequestreview-5294682098) and [the prior numbered reply](https://github.com/NVIDIA/Model-Optimizer/pull/2415#issuecomment-5801965907):

1. **Explicit builder optimization level 0: 13/13 PASS on B200.** All nine small-model conversions, the native-BF16/explicit-FP32 graph-output case, and reduced Swin FP32→FP16, FP32→BF16, and BF16→FP16 passed fresh CUDA quantization/export, full ONNX checking, strongly typed TensorRT engine building, serialization, reload, and runtime shape/dtype/finite-output checks. The mixed-output case produced `[FP32, BF16, FP32]` as intended.
2. **Default optimization level 3: 10/13 PASS; three Swin cases still FAIL with NaNs.** Those engines build and reload, but fail runtime finite-output checks. No waiver is taken. A separate same-graph BF16 Swin diagnostic passes at level 0, and captured-activation tails pass at default level 3; this indicates optimization-context sensitivity, not a proven specific TensorRT defect. The level-0 result must not be read as default-level validation.
3. **Evidence:** unchanged clean commit `03b814c1a9a85bcaa60c4135ee1e48c30c853202`, tree `ede0f480cd9dca8d57d8db4361a4ef68c439ac90`; one B200, `nvcr.io/nvidia/pytorch:26.07-py3` at `sha256:2140e699b3beaf7f96a0081fd9c9406bc3832b435cdb60dfa2d261f7d2f34a1c`, CUDA 13.3, TensorRT 11.1.0.106. Passing run completed on 2026-09-23 with harness/scheduler exit code 0. Every case recorded effective builder level 0, source fingerprints were unchanged, and all 26 artifact hashes were checked. The PR Testing section contains the command and complete environment details.
4. **Acceptance remains human-owned.** No production changes or pushes were made for this validation. The original NVFP4 scope is unchanged. Default-level Swin failures remain open; no review threads are resolved and no human sign-off is claimed. This is synthetic/random-weight build/runtime smoke testing, not pretrained accuracy or performance validation.

<details>
<summary>Passing level-0 run: SHA256 evidence manifest</summary>

- Harness: `89b038eef8c5d66102e500d184f72485fe0dbbb11ba8fa45ef189e7c76c8ac94`
- Job script: `831e8f9bae039ec383e67cc5e5f52285e957a4bee5ea3475dce4fbcbe17dbf7a`
- Completed result manifest: `27707bc62cfb5b0618c55164eaee86508a571afb5d198200f3ad470fa4875180`
- Completed job log: `11f0f2b0231d1a00d4b8b4c1fe42e4721e49461a0bc3eb30aa0156f298cd9543`

| Case | ONNX SHA256 | Engine SHA256 |
| --- | --- | --- |
| `small_fp32_to_fp16_fp8_False` | `715f75be5e2638ce931dfd61b9468dca4b417200992445e90475b8d272aa85d0` | `33fd2bf757f3003afb18a2b99f7a6bc07102c315fc34ae421908cee7e7b726d5` |
| `small_fp32_to_fp16_fp8_True` | `88cc42635cc11ae039a3d28ec33ebc4807bf1deaefa9c331c325ec198d1d4a68` | `c36ca82fef25171e80baf76a6bd5f45dd69f19f949cdfc27deb0f7916a7aad2a` |
| `small_fp32_to_bf16_fp8_False` | `9bd6f77bab5d753f78d352b7de70333df8b097b19df01b3330cb1cb11523adb9` | `c1c36f80380f8be32535b7129e52f1a353223c84e5c9f0063bd56a33e313562f` |
| `small_bf16_to_fp16_fp8_False` | `720a8c8c4e1437d480f092b0e4c8366bfbc2c69f96f280498b391bea74b8dce4` | `fb1f635fe398ce51734ba8b2a7844c5609e0213c1c449af13c381f4e888a748f` |
| `small_bf16_to_bf16_fp8_False` | `b57196e6de2b45e296c66381fc3a506dd3fc545d33d6d0cc8b9226d78173a8b5` | `368ee97d93ddf29a313067b3849b7760f46d4c321ffe48da85c596b246d1e16d` |
| `small_mixed_to_bf16_fp8_False` | `1eca4d0ee089bcfc0d832f53dce49eb5c09b99da7820fe6d48eeeb04150f65e4` | `93c44c2080e051557a5b39667b1164db820c2e8ca976c84d5a885bb9b9ecfe6d` |
| `small_mixed_to_fp16_fp8_False` | `84bec5c1cc38fd412a8ed3c1701a91152251d9f5ce5cc69d3e1ee1b9a6954cc3` | `4933bea79dfc6d50bdc34d112dfff7a9f84155f578040bb769eb421de949406e` |
| `small_mixed_to_bf16_fp8_True` | `a64d330134f829772563b63c6a948018dafabe2f37e1b486a5b6ede18ec52824` | `42196dfec02f0fbb679c263ef98921e8a6437fa93ef1ebf31c37b8f1f2344c6c` |
| `small_mixed_to_fp16_fp8_True` | `ca7717a177781de8d3751164bbd56027e92d1c8160b9f54994bd81881cf63fea` | `750cd2b4ce24f9fe7971bb99469f363d201b8bab7be662b311df49a5ff1d4898` |
| `mixed_native_bf16_and_explicit_fp32_outputs` | `10ea17bcf2c01eb753202278e6b70bd5b0d7a7cbfba42158f7b26e9513f6443f` | `d9109d40ab4603daad881ecfd271bd26b14c5f4e86e0dd412178cc89278d1098` |
| `swin_fp32_to_fp16` | `63433fe8fb9f82238957ea0e30bccefad2222c4d271d02ce10f60af90b0b827d` | `de01d35b75be3c170815ea548e0655bb160dae4402b1104038606978f31f4bc6` |
| `swin_fp32_to_bf16` | `3473fd48e4fc28343ea2fb4ca101ea524f1183ea13127ac4c05059be98adff7f` | `5ca55c694e63971f60e803f9dfbd5e95f4507d9465220b998db94293394eab50` |
| `swin_bf16_to_fp16` | `3920e754a1278525b33745f665f1e35b56286ac21149a81f44c8eaa4b5891e79` | `8a8c57e50f7492d7b78c4b6d51e090607335bf7656da7cd986cdcc5e1126ab8e` |

</details>

> 🤖 _Generated by Codex (AI agent)._


## Review (6)

### coderabbitai[bot] · 2026-09-11 · APPROVED

(no text)

### cjluo-nv · 2026-09-11 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Nudge: the branch change itself is sound, but the new tests mock out both converters so nothing verifies the actual mixed-dtype fix, and the FP16 NVFP4 path now skips AutoCast's opset upgrade.

Needs action:
- [ ] Confirm the opset regression in `modelopt/torch/_deploy/utils/torch_onnx.py`: `convert_to_f16` bumped NVFP4 graphs to opset 23 (`get_min_opset_for_precisions`), the `convert_float_to_float16` branch does not, so default exports now ship opset-20 metadata over opset-23 FP4 `DequantizeLinear` — fix it here or say why it's acceptable.
- [ ] Add an end-to-end check that the exported FP16 NVFP4 graph has no mixed float-type elementwise inputs; `tests/unit/torch/quantization/test_onnx_export_cpu.py::test_nvfp4_exported_onnx_is_topologically_sorted` shows a CPU-feasible NVFP4 export pattern.
- [ ] Explain whether `weights_dtype="bf16"` + NVFP4 still hits the same TensorRT parse failure, since it keeps routing through `convert_to_f16` → `GraphSanitizer.find_custom_nodes`.

No action needed:
- The added `weights_dtype == "fp16"` guard is a no-op for BF16 (the earlier `ValueError` already covers FP8/other quantizers), so the BF16 path is genuinely preserved.
- PR body notes the change is Codex-authored without Claude approval, so a human pass is warranted regardless.

<!-- bot-review sha=51493d4e8fdc3fc1eec443b1d5c59f7a0369f4bc -->

### cjluo-nv · 2026-09-11 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Nudge: all three prior concerns are fixed with real code and real CPU coverage, but the PR quietly turns two previously-working NVFP4 conversions into hard errors and the agent-authored change still wants a human pass.

Needs action:
- [ ] Document the new hard failures in `CHANGELOG.rst`: `weights_dtype="bf16"` with FP32 params + NVFP4, and `weights_dtype="fp16"` with BF16 params + NVFP4, previously ran through `convert_to_f16` and now raise `ValueError` in `modelopt/torch/_deploy/utils/torch_onnx.py`. The PR body still marks this backward compatible.
- [ ] Confirm the `weights_dtype="fp32"` NVFP4 path: the new `if uses_fp4:` opset block runs there too and `nvfp4_exporter.post_process` now stamps MatMul outputs as FP16, so that graph can still carry mixed FP16/FP32 elementwise inputs — say whether it is out of scope or add it to `test_nvfp4_deploy_export_has_consistent_elementwise_types`.
- [ ] Have a human review the Codex-authored commits before merge.

No action needed:
- :heavy_check_mark: Resolved since the last review: the opset-23 upgrade before precision conversion, the real CPU NVFP4 export test asserting no mixed-float elementwise inputs, and the BF16 no-op routing.
- Refactor of `test_nvfp4_exported_onnx_is_topologically_sorted` into `_make_cpu_nvfp4_model` keeps coverage intact.

<!-- bot-review sha=1ffc34f89a28ba846dcea971d0af45cf6eccd868 -->

### cjluo-nv · 2026-09-12 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Nudge: the two prior code concerns are resolved with real CPU coverage, but hardware acceptance is stale on current head and one BF16 branch in the exporter is unexplained.

Needs action:
- [ ] Rerun or explicitly waive the Blackwell/TensorRT engine build for the current head; the PR body says it was not repeated after the final exporter change.
- [ ] Explain (ideally as a code comment) why the BF16 branch in `modelopt/onnx/export/nvfp4_exporter.py::_cast_input_dtypes` re-stamps the node output value_info to BF16 instead of inserting a boundary Cast like the FP16 path — on a graph with any BF16 initializer this silently retypes outputs whose consumers are still FP32.
- [ ] Have a human review the Codex-authored commits and the declared backward-incompatible `ValueError` behavior before merge.

No action needed:
- :heavy_check_mark: Resolved since the last review: the `CHANGELOG.rst` entry for the new FP32→BF16 / BF16→FP16 hard failures, and the `weights_dtype="fp32"` mixed-type path (Gemm bias cast + output boundary cast, covered by the new parameterized `elementwise`/`gemm` CPU tests).
- The output cast is skipped when a node output has no value_info (e.g. after a failed shape inference), which just restores pre-PR behavior rather than regressing.

<!-- bot-review sha=2b8c579cb78e8706c6323bb8692d2c1fc0f95079 -->

### cjluo-nv · 2026-09-18 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Nudge: both prior code concerns are now fixed with real CPU coverage, but the Blackwell acceptance was waived rather than run and the backward-incompatible `ValueError` behavior in agent-authored code still needs a human call.

Needs action:
- [ ] Have a human sign off on the Codex-authored commits and the new `ValueError`s in `modelopt/torch/_deploy/utils/torch_onnx.py` (FP32→BF16 and BF16→FP16 NVFP4 now hard-fail); CHANGELOG documents it, the PR body still needs the compatibility flag to match.
- [ ] Decide whether the waived current-head Blackwell/TensorRT engine build is acceptable, or rerun it once a B100/B200/SM120 host is available.
- [ ] Confirm the BF16 re-stamp in `nvfp4_exporter.py::_cast_input_dtypes` is safe when a BF16-weighted node output *is* a graph output under `weights_dtype="fp32"` — that path changes the declared model output dtype with no Cast and isn't covered by `test_nvfp4_deploy_export_preserves_mixed_precision_boundaries`.

No action needed:
- :heavy_check_mark: Resolved since the last review: the global-precision BF16 retyping bug (now derived per quantized weight, with an inline comment) and the new mixed FP32/BF16 export regression test.
- Refactor into `_make_cpu_nvfp4_model` keeps the original topological-sort test coverage intact.

<!-- bot-review sha=848137557947dac1e91a6ba0498893b4bb6b45ac -->

### cjluo-nv · 2026-09-23 · COMMENTED

> _Bot review (claude-opus-5) — DM the bot to share feedback._

Nudge: prior code findings are fixed, but the new AutoCast-wide changes in this round plus the still-open BF16 re-stamp question need an owner's call before merge.

Needs action:
- [ ] :speech_balloon: Author replied that the BF16 re-stamp is required because `TRT_FP4QDQ` lacks shape inference — still needs the graph-output case: in `nvfp4_exporter.py::_cast_input_dtypes`, a BF16-weighted node whose output *is* a graph output is retyped with no Cast under `weights_dtype="fp32"`. Confirm it is unreachable or cover it in `test_nvfp4_deploy_export_preserves_mixed_precision_boundaries`.
- [ ] Justify hard-coding `TRT_FP4DynamicQuantize` and its exact FP4/FP8 output signature inside `graphsanitizer.find_custom_nodes`, or pass the skip as an explicit flag from the NVFP4 caller — this changes TRT inference for every AutoCast user with that plugin.
- [ ] Add AutoCast coverage for the widened input retype in `precisionconverter.convert` (`elem_type in ONNX_TYPES`): an FP16 graph input is now silently declared BF16 when `keep_io_types=False`.
- [ ] Have a human sign off on the Codex-authored commits and decide whether the waived current-head Blackwell engine build is acceptable.

No action needed:
- :heavy_check_mark: Resolved since the last review: the per-weight precision derivation, the mixed FP32/BF16 export regression, the CHANGELOG policy entry, and the sign-preserving initializer clamp (now tested).
- 207 core-logic lines — under the size budget.

<!-- bot-review sha=794aa396ce7d782f0e79a58e652372c40cf792f6 -->
